apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-image-indexer.fullname" . }}
  labels:
    {{- include "nft-image-indexer.labels" . | nindent 4 }}
data:
  config.yaml: |
    cloudflare:
      account_hash:
      account_id:
      api_token:

    image_db:
      dsn:

      # 1 = Silent
      # 2 = Error
      # 3 = Warn
      # 4 = Info
      log_level: {{ .Values.serviceConfig.dbLogLevel | default 2 }}

    store:
      db_uri:
      db_name: nft_indexer

    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

    thumbnail:
      cache_period: {{ .Values.serviceConfig.cachePeriod | default "144h" }}
      cache_retry_interval: {{ .Values.serviceConfig.cacheRetryInterval | default "24h" }}
