apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-image-indexer.fullname" . }}
  labels:
    {{- include "nft-image-indexer.labels" . | nindent 4 }}
data:
  config.yaml: |
    cloudflare:
      account_id:
      api_token:

    image_db:
      dsn:
      log_level: 2 # error

    store:
      db_uri:
      db_name: nft_indexer

    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

