{{- $k8sVersion := .Capabilities.KubeVersion.GitVersion -}}

{{- if .Values.ingress.enabled -}}
{{- if empty .Values.ingress.hosts }}
{{ fail ".Values.ingress.hosts should not be empty when ingress is enabled" }}
{{- end }}
{{- $fullName := include "nft-image-indexer.fullname" . -}}
{{- $tlsSecretName := include "nft-image-indexer.tlsSecretName" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nft-image-indexer.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.external_dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ range $index, $value := .Values.ingress.hosts }}{{ if ne $index 0 }},{{ end }}{{ $value.host }}{{ end }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.certificate.enabled }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host }}
      secretName: {{ $tlsSecretName }}-{{ .issuerRef.name }}{{- if .uniqueSuffix }}-{{- .uniqueSuffix }}{{- end }}
      privateKey:
        rotationPolicy: Always
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- with .paths }}
          {{- range . }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
          {{- else }}
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
