secrets:
    ethereum:
        worker_account_mnemonic: null
        rpc_url: null
        ws_url: null
    store_db_uri: null
    account_db_uri: null
    opensea_api_key: null
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/1965b82b-4f9b-4c0d-9dfa-d575132528d3
          created_at: "2022-05-10T02:59:47Z"
          enc: AQICAHi/zaXXtoouOl3wGZO6fSpK7NYlac8Ro+bHbPaUjUK5fQGKqoMRuAWxT+AqCsgzCflIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW6mX2+UZ0aEAK36UAgEQgDusEEe3cHsbmMNeHRSp0xE501rCSI8hkduRv342PaQY6vcjdlQWKhSjxc7MWB1lxwD5CCI8Q0ee5XdrkA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-10T02:59:47Z"
    mac: ENC[AES256_GCM,data:A8mZ5A3zLpf9XP5lFjPwv9J5TN9D1BLKesGEbDE/BmGnU8GkAHPMtDn869Mwib1wgl5IlYr6BS1Ze45VfppGfKqtJU/7W6Eq0IISGkoF0jI9nagyqx+THAS2MlTYvxeNx0QvQQ1JHrP83Upl5lwIpgKlzIQiBdyuA5XRUVjO3go=,iv:icm7qrEVTB5N80VfydDpHP+YlNrHKtf/CMYacPVWRkE=,tag:DPCCp6LXl+uW+eXc9C3UsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
