secrets:
    store_db_uri: ENC[AES256_GCM,data:20EnSWNRn6JzCxuPwWHqsz/0iI+k3GhZNAi4IcLdLIffCrt1BQSUPq0oVzkEoY5NZpuOC4pjDsJ84/dLyimb2VxPYnGLTjsMqnNCwl2059ZKe1we3kqut6lDW7IJGQnCj9p71Z9rNE8nJWLlbz8UIgWXo94g+nTpwEdnWZU9kZs=,iv:0Dtzj6A1WtFOolZaoHibCGcluh59ZqQUvju5oEPCJIM=,tag:soGWbRkPs6yT/Fk7V4AFNA==,type:str]
    image_db_dsn: ENC[AES256_GCM,data:muLK3JqkP0twxUdLbG7d39qnXnsPFSICx8Gj82LYoaGQSBPcJ94FuFZaK+5sHEAnSH25JyVuI1NajFnhiN43Ga0MIDRtWy9jseQInaRGMXmHKON2mJzcvd86SSCMb4OmJotwDltdH5q+tncol50FU0q5/xkQZFUwSss3qRdmezfjXMMhnIAkW1AD/cB1CIA5SIfsf2UxCCrgVRX2I5AwORxpTa4S9iq2Rdce25ft,iv:HKgDcov+h9Y525lbG+H052Uc10JTnVfesjzJX/CclRA=,tag:p8L/NU2ZKdRjU0FDaFaR4w==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:I1ncY+5tRgt9tQqUnNlBkJDdly3vE3ho7omyZmuKJT0=,iv:0nP/1ZeWaKB0jja0Z2W8woscUgaIiLrgd93rK666uJ4=,tag:0IHkm/7spbh3yOSYyiwdGQ==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:xTpKpFTRc5QeGo8Mr1cOOzQQdB3QXxYVuFAddj7cxzBnHjHlGH4n4g==,iv:rQTXYi3UPbb861P0+9WIpj04NaBXTWwgOPIiv+/87Ew=,tag:ilthmtGbW/QWdpsHXAm6Pg==,type:str]
    pinata_jwt: ""
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2022-10-11T08:40:34Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQH5lH7T3X3HW5v6po1VCG0XAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGvIKz/DFs0B7TcIUAgEQgDuT2M883CMVrftfcBcqz2p0anVfFy34Mbtc/rgh6GbHRRORplfNhOQTL/rOLi7h2+m4oCOjTghz1+wWsQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T08:40:34Z"
    mac: ENC[AES256_GCM,data:3Siiqg2v+rwD1s+3I3rCpGy/y6ux24tzwE8jUKkc128w3bE9hRCgiitXQG03G5BCflQtEekW9q+5QP2obaFAPYpIAVwDNjHKumBZC4ytjGnreE+1esiPsyjyNFSV144kN0bX/7usKGP8AdhX/rVU6e34YDsms2sjw7PG7KzS6yQ=,iv:YVE2l1cUfFP5wdcTI8bQQEWGUG3LRvKhC0kwZ/bPNRQ=,tag:CAITVtlyDowR1Ai+puucgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
