secrets:
    store_db_uri: ENC[AES256_GCM,data:HVZs5D+tVd7vYNpkkgwnqfIhAGRqTvXDx3C+DnaAR/lRBuYzqM5JR64CLneib3a3HclwWBlzKdUpfMOaHkQNTHdzCZpahmyBmZUd6njSK3wNA5SNB4NfVQII1n3sClpw/tgcXe91iwE=,iv:kqMg4uM+iPXJTr3xO2TTDKRLtA/gVU2yWR4Z1RKM4c4=,tag:yYtTsIF6W90JLDIEiroPiw==,type:str]
    image_db_dsn: ENC[AES256_GCM,data:HJdXapTOZe8MZhLcpWzLcmFSZeq4Tm5JtXC3DakGNkhrYZRd9jrRULbZODDzmZl56H4Hgh+ePHvhzwE899aeiKsSTXNYKI2WzGUdwDkqW6aC0GveW/AXCtC6APYd+JtIpJWwYsrsrDEwNP2GqerKO02ojuF2QeDoOX29SbOMrAbCrFRUcMV5UPR8lcat0I5pHpt/P5kcuPcGGWycazVO44oQK7m/hjNyWFz/wcaXz6P3ta06PpkiRJi0UJkOpma1MynWN1Ig7Unwxc2nJwaaFj1WVuS4FUKK1uo=,iv:jvU/o/xE8EwHlSGYP/NRmW6r/pLbOAOOhcppBTSPT2s=,tag:NyOn4nTzGekhJ3fS3lnxxg==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:V2Hxu7VRyz79yQwL0BgyZ/+brUW3U8lRGIYwVMCyS1M=,iv:CHybAgtegMXeC6Abuf0uQLq4cmC8acmEh7KbSLiCsxI=,tag:HHHMuAXT3cQzpx3slT6XtQ==,type:str]
    cloudflare_account_hash: ENC[AES256_GCM,data:1RjblCTuvRJMdPnlgQLjptz4TMl8Hw==,iv:4IfdYGnII/6oN1hB6ISmE2RqjSYUGY9yAG6Te9TekH0=,tag:lseUwyejilmM5ieeY5wpLg==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:wJOywVaTRC4JTj1fWiYyh9DHho3remFhh8PnagXwwGPhreDsbJs8TA==,iv:3EZeymGEvZ0XnG9MBezKdIWMA7uPvhx/4JvbBebsbCQ=,tag:aWhxZcqyVsm/18KFf2cw7A==,type:str]
    pinata_jwt: ""
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2023-03-14T04:06:37Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQGgI+yi+cOmNlvQudhLjCyTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMN788hpVjeybheW1nAgEQgDu3gnS8ycGYmDWBuVeJUlxpD1VIQWnPao20fl8gROuA5vtikU1v+GnPS1MWvrQNbTLzqStYrRTCB+D/hQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-14T04:06:37Z"
    mac: ENC[AES256_GCM,data:vAF3Ml3Yzgn0/7BRs0KFOpcdKBpiwkdRsPFpZ9PbYluY6uuajeaGKYl6Fjn73GPD75hFUR4+h9kUzMKgnNgPd5DFi1e9nhtJv03Ck59l5oHDxnoKee0PV0G6pLNkfAkSfjjuRsOLlLvcC+oFcqoaW5c8UgQ9s98Dltz3y1ZR/L4=,iv:dUuWGmhup2jn9HhtIgQnUHbNoTdirXcw7vmPgJAsu+o=,tag:Qk7/EX2P4Wq38F7weNmaPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
