# Options for analysis running.
run:
  # Number of CPUs to use when running golangci-lint.
  # Default: the number of logical CPUs in the machine
  concurrency: 2

  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 10m

  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2

  # Include test files or not.
  # Default: true
  tests: false

  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path,
  # including the path prefix if one is set.
  # Default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  skip-dirs:
    - contracts
    - scripts
    - helm-chart
    - protos

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: true

  # Which files to skip: they will be analyzed, but issues from them won't be reported.
  # There is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not, please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  skip-files: []

  # If set, we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # Default: ""
  modules-download-mode: readonly

  # Allow multiple parallel golangci-lint instances running.
  # If false, golangci-lint acquires file lock on start.
  # Default: false
  allow-parallel-runners: true

  # Allow multiple golangci-lint instances running, but serialize them around a lock.
  # If false, golangci-lint exits with an error if it fails to acquire file lock on start.
  # Default: false
  allow-serial-runners: false

  # Print avg and max memory usage of golangci-lint and total time.
  # Default: false
  print-resources-usage: true

  # Show statistics per linter.
  # Default: false
  show-stats: true


linters:
  # Disable all linters.
  # Default: false
  disable-all: false
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gosec
    - gosimple
    - whitespace
    - bodyclose
    - cyclop
    - dupl
    - exhaustive
    - loggercheck
    - revive

severity:
  # Set the default severity for issues.
  #
  # Default: ""
  default-severity: ""

  # If set to true `severity-rules` regular expressions become case-sensitive.
  # Default: false
  case-sensitive: true

linters-settings:
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: warning
    # Enable all available rules.
    # Default: false
    enable-all-rules: true
    # Sets the default failure confidence.
    # This means that linting errors with less than 0.8 confidence will be ignored.
    # Default: 0.8
    confidence: 0.7
    rules:
      - name: rule.blank-imports
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.context-as-argument
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.context-keys-type
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.dot-imports
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.error-return
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.error-strings
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.error-naming
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.exported
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.increment-decrement
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.var-naming
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.var-declaration
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.package-comments
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.range
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.receiver-naming
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.time-naming
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.unexported-return
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.indent-error-flow
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.errorf
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.empty-block
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.superfluous-else
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.unused-parameter
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.unreachable-code
        severity: warning
        disabled: false
        exclude: [""]

      - name: rule.redefines-builtin-id
        severity: warning
        disabled: false
        exclude: [""]