FROM golang:1.24.0-alpine3.21 AS build

RUN apk add --no-cache gcc musl-dev

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/tezos-event-emitter ./services/tezos-event-emitter

# ---

FROM alpine:3.21
ARG dist=0.0

RUN apk add --no-cache curl

COPY --from=build /go/bin/tezos-event-emitter /tezos-event-emitter

ENTRYPOINT ["/tezos-event-emitter"]