FROM golang:1.24.0-alpine3.21 AS build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/ethereum-event-emitter ./services/ethereum-event-emitter

# ---

FROM alpine:3.21
ARG dist=0.0

RUN apk add --no-cache curl

COPY --from=build /go/bin/ethereum-event-emitter /ethereum-event-emitter

ENTRYPOINT ["/ethereum-event-emitter"]