# syntax=docker/dockerfile:1.2
FROM golang:1.21-alpine3.18 as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/image-indexer ./services/image-indexer

# ---

FROM 083397868157.dkr.ecr.ap-northeast-1.amazonaws.com/nft-indexer:chromep-0.1.0
ARG dist=0.0

COPY --from=build /go/bin/image-indexer /image-indexer

USER root
RUN apk add --no-cache ffmpeg

ADD services/image-indexer/config.yaml.sample /.config/config.yaml
