FROM golang:1.24.0-alpine3.21 AS build

RUN apk add --no-cache gcc musl-dev

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ADD go.mod go.sum ./
RUN go mod download

ADD . .

RUN go build -o /go/bin/provenance-indexer ./services/provenance-indexer

# ---

FROM alpine:3.21
ARG dist=0.0

COPY --from=build /go/bin/provenance-indexer /provenance-indexer

ENTRYPOINT ["/provenance-indexer"]