FROM golang:1.24.0-alpine3.21 AS build

RUN apk add --no-cache gcc musl-dev

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ADD go.mod go.sum ./
RUN go mod download
    

ADD . .

RUN go build -o /go/bin/api-gateway ./services/api-gateway
#RUN go build -o /go/bin/replace-ipfs-link-by-objkt-cdn ./command/replace-ipfs-link-by-objkt-cdn

# ---

FROM alpine:3.21
ARG dist=0.0

COPY --from=build /go/bin/api-gateway /api-gateway
#COPY --from=build /go/bin/replace-ipfs-link-by-objkt-cdn /tools/replace-ipfs-link-by-objkt-cdn

ENTRYPOINT ["/api-gateway"]