FROM golang:1.21-alpine3.18 as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go install github.com/feral-file/ff-indexer/services/grpc-gateway

# ---

FROM alpine:3.18
ARG dist=0.0
COPY --from=build /go/bin/grpc-gateway /grpc-gateway

ADD services/grpc-gateway/config.yaml.sample /.config/config.yaml
