FROM golang:1.21-alpine3.18 as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/provenance-indexer ./services/provenance-indexer

# ---

FROM alpine:3.18
ARG dist=0.0

RUN apk add --no-cache curl

COPY --from=build /go/bin/provenance-indexer /provenance-indexer

ADD services/provenance-indexer/config.yaml.sample /.config/config.yaml
