# syntax=docker/dockerfile:1.2
FROM golang:1.21-alpine3.18 as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go install github.com/feral-file/ff-indexer/services/ff-indexer-grpc

# ---

FROM alpine:3.18
ARG dist=0.0
COPY --from=build /go/bin/ff-indexer-grpc /ff-indexer-grpc

ADD services/ff-indexer-grpc/config.yaml.sample /.config/config.yaml
