FROM golang:1.24-bullseye AS build

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

WORKDIR $GOPATH/github.com/feral-file/ff-indexer

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/image-indexer ./services/image-indexer

# ---

FROM chromedp/headless-shell:latest
ARG dist=0.0

COPY --from=build /go/bin/image-indexer /image-indexer

USER root
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/image-indexer"]