# syntax=docker/dockerfile:1.2

# SPDX-License-Identifier: ISC
# Copyright (c) 2019-2021 Bitmark Inc.
# Use of this source code is governed by an ISC
# license that can be found in the LICENSE file.

FROM golang:1.20.4-alpine3.18 as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/bitmark-inc/nft-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/nft-image-indexer ./services/nft-image-indexer

# ---

FROM 083397868157.dkr.ecr.ap-northeast-1.amazonaws.com/nft-indexer:chromep-0.1.0
ARG dist=0.0

COPY --from=build /go/bin/nft-image-indexer /nft-image-indexer

USER root
RUN apk add --no-cache ffmpeg

ADD services/nft-image-indexer/config.yaml.sample /.config/config.yaml
