# syntax=docker/dockerfile:1.2

# SPDX-License-Identifier: ISC
# Copyright (c) 2019-2021 Bitmark Inc.
# Use of this source code is governed by an ISC
# license that can be found in the LICENSE file.

FROM golang:1.19.3-alpine as build

RUN apk add --no-cache git gcc musl-dev

ARG GITHUB_USER=bot
ARG GITHUB_TOKEN=token

RUN git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR $GOPATH/github.com/bitmark-inc/nft-indexer

ENV GOPRIVATE=github.com/bitmark-inc

ADD go.mod .
RUN go mod download

ADD . .

RUN go build -o /go/bin/nft-event-processor-bitmark-emitter ./services/nft-event-processor-bitmark-emitter

# ---

FROM alpine:3.14
ARG dist=0.0

RUN apk add --no-cache curl

COPY --from=build /go/bin/nft-event-processor-bitmark-emitter /nft-event-processor-bitmark-emitter

ADD services/nft-event-processor-bitmark-emitter/config.yaml.sample /.config/config.yaml
