helmDefaults:
  kubeContext: arn:aws:eks:ap-northeast-1:083397868157:cluster/{{ if hasKey .Values "clusterName" }}{{ .Values.clusterName }}{{ else }}DevelopmentEksStack01{{ end }}

releases:
- name: nft-event-subscriber # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-event-subscriber  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: event-subscriber
  values:
  - helm/environments/nft-event-subscriber/{{ .Environment.Name }}/values.yaml
  secrets:
  - helm/environments/nft-event-subscriber/{{ .Environment.Name }}/secrets.yaml

- name: nft-image-indexer # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-image-indexer  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: image-indexer
  values:
  - helm/environments/nft-image-indexer/{{ .Environment.Name }}/values.yaml
  secrets:
  - helm/environments/nft-image-indexer/{{ .Environment.Name }}/secrets.yaml

environments:
  development:
  production:
    values:
    - clusterName: ProductionEksStack01
  staging:
    values:
    - clusterName: ProductionEksStack01
