helmDefaults:
  kubeContext: arn:aws:eks:ap-northeast-1:083397868157:cluster/{{ if hasKey .Values "clusterName" }}{{ .Values.clusterName }}{{ else }}DevelopmentEksStack01{{ end }}

releases:
- name: nft-indexer # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-indexer  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: indexer
  values:
  - helm/environments/nft-indexer/{{ .Environment.Name }}/values.yaml
  {{- if env "GITHUB_SHA" }}
  - image:
      tags:
        api: "api-{{ env "GITHUB_SHA" }}"
        background: "background-{{ env "GITHUB_SHA" }}"
        provenance_indexer: "provenance-indexer-{{ env "GITHUB_SHA" }}"
        account_token_indexer: "account-token-indexer-{{ env "GITHUB_SHA" }}"
  {{- end }}
  secrets:
  - helm/environments/nft-indexer/{{ .Environment.Name }}/secrets.yaml

- name: nft-event-subscriber # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-event-subscriber  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: event-subscriber
  values:
  - helm/environments/nft-event-subscriber/{{ .Environment.Name }}/values.yaml
  {{- if env "GITHUB_SHA" }}
  - image:
      tags:
        eventSubscriber: "event-subscriber-{{ env "GITHUB_SHA" }}"
  {{- end }}
  secrets:
  - helm/environments/nft-event-subscriber/{{ .Environment.Name }}/secrets.yaml

- name: nft-event-processor # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-event-processor  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: event-processor
  values:
  - helm/environments/nft-event-processor/{{ .Environment.Name }}/values.yaml
  {{- if env "GITHUB_SHA" }}
  - image:
      tags:
        eventProcessor: "event-processor-{{ env "GITHUB_SHA" }}"
        ethereumEmitter: "event-processor-ethereum-emitter-{{ env "GITHUB_SHA" }}"
        bitmarkEmitter: "event-processor-bitmark-emitter-{{ env "GITHUB_SHA" }}"
  {{- end }}
  secrets:
  - helm/environments/nft-event-processor/{{ .Environment.Name }}/secrets.yaml

- name: nft-image-indexer # name of this release
  namespace: autonomy{{ if eq .Environment.Name "staging" }}-staging{{ end }}
  chart: helm/charts/nft-image-indexer  # the chart being installed to create this release, referenced by relative path to local helmfile
  labels:
    app: image-indexer
  values:
  - helm/environments/nft-image-indexer/{{ .Environment.Name }}/values.yaml
  {{- if env "IMAGE_TAG" }}
  - image:
      tag: {{ env "IMAGE_TAG" | quote }}
  {{- end }}
  secrets:
  - helm/environments/nft-image-indexer/{{ .Environment.Name }}/secrets.yaml

environments:
  development:
  production:
    values:
    - clusterName: ProductionEksStack01
  staging:
    values:
    - clusterName: ProductionEksStack01
