secrets:
    store:
        db_uri: ENC[AES256_GCM,data:rqJLCCuWkqiZYjBtSbHvf2Kzolk9EF0EUkkj9leVeBuuX5UGZjEvmc6gUERTzQQjq6kGKCM9C+aDxgfMF9O5+0d5Q1t8/6Gfs2K936cSMAZN+RuXSHAlCF3Oy7M3wG/rVq8vZPLVXGfBG5MrVpLHnShKeDsQNDLKFEdUSOs8/7KFkA8aqaCgvUdojrU+aD4=,iv:nsfyVsJoUmY2QE7VbLbdYw24XjmWvfTcr3dDAoEcgn0=,tag:SJ5QJ+oRXzVjJQ9ngaFLag==,type:str]
        db_name: ENC[AES256_GCM,data:utR9a+8BIMeVGIc=,iv:YPrySg7DqKaOC5sVRl99TQCyZLQenUEGUpUQTVLWrK4=,tag:TeQwMdu7EQxoKL1UWqhcGQ==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:CCWFz0FFZVLXcd1XeIIEjN8331d8c6FWPPgy5oxyxOk=,iv:78IkDEZV/5ydpxLoeTCpXjQRXq/vJ55fAyNsMJpN9Fk=,tag:pbi55YqUH/lZCY19i/HABA==,type:str]
        admin_api_token: ENC[AES256_GCM,data:tOBBEuYhAFupDuwpheQe,iv:+a+cgm1UTwEsp2YCX0n6tIpl0TzoO0m/y23L4E2PIdI=,tag:vsoEOjbPTW2CLk9Roj1rgA==,type:str]
    opensea:
        api_key: ""
    ethereum:
        rpc_url: ENC[AES256_GCM,data:agKft41X6SsI7tMbr7eWtFdc2X7tFpDDwLH72z4i/VbzssF8H30BPaywf4lKqKE=,iv:u93ki+lFIbooLb08r9cpTI4n+VDrMO+s2gI0skhvAeE=,tag:Ur0KakFjFOBFVbm4BJi1OQ==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:xNMEpk2xHnEMaW5d8u2TF/d7uLwyed7ODRtCffKnQDVpwI3U5kscEPnShltVSZRl4gqP0eZsKzK2JluR5SsPw+Jtmkw1mZMKCVXMQpjvwhOuvzWu3WnN8OV0Dx0u2Gk0CX/+SZR/mY2mjc7mC3FU/JFMKVL+W0EXHFpyFZo09q5Eqe9QqJ3upRuIgWHBiwo=,iv:6vKIzclbT2E3Nx6ag/YklDcvdF4FGx0lGw0vtb0P0wo=,tag:Tili8qZEkviblxXWbxcQ8g==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:ykmuJUnkhuMgjUsYhBK42l3EJNU7XdmiOJ78akOHlhqTa0mQo1w5hBtUYrGL3+XhEdyL1v7awt7Ffw+KXg==,iv:akvZxugKxYxkP0771zR6FtWbPgb/nh/f/e3aLEwEeNU=,tag:SYJAooXoEWwTFjvnTVVANw==,type:str]
    sentry:
        dsn: ENC[AES256_GCM,data:3whQo5kDd7FKuPSIso4LqjguU+RPda3UV5EFPKvjZBTWhvHYwIrFkCMMSrh32UkCj9Cy6+mLWrv1ydpISCmXVUA6tjwEO919dg==,iv:ZJkA1jAzLrgSnAwXFOPYsgIGNAoqTbuHrLw1vO1E4fU=,tag:i8FQo7JAJESDWzeM8UnGMQ==,type:str]
    aws:
        access_key_id: ENC[AES256_GCM,data:PO4jGvilVki9+MISYVYM3CDUO/s=,iv:j6+BCbiQdgzhbWhpxQiiZnTvRy6E9cTiIsi8xMUdj/g=,tag:b2JPc2k6Rsneo5kEtyV3yQ==,type:str]
        secret_access_key: ENC[AES256_GCM,data:7U4SDiPmrNb8ptyaFp83YjUSPzWibGzeuy2icaEQNzFdW1XvySzn4w==,iv:RQo+MqQniDEISWx9+S4qOxxTmNeWVE+6oG80/wLgD8k=,tag:PL/uQWc176kwL7mUxVOP4w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/2fc00fb4-6f1c-45b2-a247-41a72fb2006a
          created_at: "2022-11-22T03:18:19Z"
          enc: AQICAHhj5BWgGUcW7rT6Wr8RMMkOteG0zlIjyc3aMstW74cZzgEcPIIEw2UbRZipikzZiDCDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1S+BEAyk1+Y0USs/AgEQgDtY4b777NOoSViYAHeTz73aGyb5VeVDXUnWRd0i85/jjw1DE10/y37Si6Eq8ta/KFhAfZcWRR2XVHFqlQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-22T03:18:19Z"
    mac: ENC[AES256_GCM,data:RqFQf5mzJtsBag6R82BxoUiydazBtxituM4BVDFqflJnRmOYTsnc96MLzCWy1MfAbTrD9VrgoLeEN6+6+3MxfWhhpxcHDLKiW45KueG8AE6JbuXkYT8RLSfpSwfRU3IcsUKJ/635EeCd9VkIg3LdqRe/I9W1rcIKRvt5Ix8pu2U=,iv:di5K/wOXYgWkFobOJd10xzS0JD74IYYuhbxkgEWf29U=,tag:dGW+Ol/N9lVwveb2UEBfVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
