secrets:
    store:
        db_uri: ENC[AES256_GCM,data:AUB8Dy2gLjypgiiIpf33enK5yy5cV/ZRb59sd+wpeyT/w3CjVvFKeuZt6kAKVyrwv4qErOg6VZAbVsHr9RLbN0hYGBJ4F8YNoH7cWwYr6Oiz4kc997W+GYpLb98oyXo2RmIDaKHSK8RyCiltEXutg+duGwIT6Ns4RC3RHKYW3rSQEh9d+CTznMDdEQ3CX94=,iv:zHUGQDw0rmFr6A5X4NpewucND8YUpK5n9DhHgU71KeY=,tag:wxel+B/UsTILqbOpJh2lOA==,type:str]
        db_name: ENC[AES256_GCM,data:fOQuxJPxTOCEIuc=,iv:V8JHqq+iMOfUoxa8aA90t1PoX4QZRvw1vir1B/pmbLM=,tag:C+cwyPOjqwgAwp2653bTMw==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:IbwuIpVJ6bSbL4TRfREidPhtxZzUiluk5dtPuzomNO0=,iv:HP/EC2+Ao/XxsmgF6/ZpfdpQmOavgGdHlUu9NUpAPn8=,tag:l1hz4i4h1XJ4wT4IBdvzvQ==,type:str]
        admin_api_token: ENC[AES256_GCM,data:PhnsZxFyIO8Khaem77CD,iv:Czx85r/wXjXeqq9tP9shxkEmvc664j5wOEQ2PfR595k=,tag:5RGTEQCNwUZd0w93z51eIQ==,type:str]
    opensea:
        api_key: ""
    ethereum:
        rpc_url: ENC[AES256_GCM,data:IiAnk7dANgVBxgXbtYQiC4mCAgpDXxyJIWMDj9pXBNrNCSxjmMhk/nGQkU8JTWLMSrgw+FiIG1crYWvf,iv:FG64CgRHiTeJIikfLSqnzPwpudsFnHmgQdxry+ex3B0=,tag:mm1aA/cOoUpDaozX95Uf7g==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:9iVpORyqROIQYBVZRwQcMMTkJbcb8vIi8KB2cwpOOSEBR05uhAHPmoohgBXW9UZeK1S66RxPvrr+0xQb81ZXIEGRZc+x9PXzVa3fqfG5l4my8aeqgbED+6ywsbgNn+q1Dg1WunikmLbuM07Lj+qoHLUlkLBuT4roy0mhhqmvBAoKfPSISTIb6V+Lhpd6lfI=,iv:S9hohRbz++OrhR01sxQP5wYDcnutKcYT8WF/sVrApUs=,tag:diV7klWWAUqhDnjc9dY1AQ==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:B4JkBAAzXb8nETfSaMdynqgNantcXjTNnORvWlQwQF4elExEJqLXIkHbeGYlyRueP7NxvxYefBaKBdH0Ng==,iv:w+e7wJtSNp+wBC2NOBCbK/HZ1I/BUo1qtW2vDYOdTBA=,tag:/UWTTrWDzsVS2ZvsMGERuA==,type:str]
    sentry:
        dsn: ENC[AES256_GCM,data:Xr5GcSnnflX+saHllkU85D1T980tFRwdxWUNv6E6V2/GpJZSnsugOF27crdGwV8Gi0P5VlyruPQdDRjxjj6hkspjI9H2KfQjLQ==,iv:qQKVQuLJL4AZs9WNYAf1sfGq/Hd1z7yR0Cx9ZHZtGEM=,tag:aF/zJdI/PAipaPkEg572VQ==,type:str]
    aws:
        access_key_id: ENC[AES256_GCM,data:kEIgRFnJf0VC8EFhwur7wJ9x8OM=,iv:Zw0xvGnIgmmYN7gKGM6s1LXeuIRjsiWigzI9q5hxRFI=,tag:SLmP59smdncG3qjD99PYZg==,type:str]
        secret_access_key: ENC[AES256_GCM,data:KhAtQKUvB+UYUhcpU9MSL9cSisk3La8MorfNYHkeO7emIqVKDWGeNQ==,iv:sVICDDpE6wn2rtGQyD8uuhltrki2NNbYJBOI7U2wSnw=,tag:Bh+ildhPyCUtRl6eTLXKiw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/2fc00fb4-6f1c-45b2-a247-41a72fb2006a
          created_at: "2022-11-16T07:55:41Z"
          enc: AQICAHhj5BWgGUcW7rT6Wr8RMMkOteG0zlIjyc3aMstW74cZzgHS3cCGW/sT3r9sOZWsm49dAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwbkkKYviaYtYb1TEAgEQgDuoOVKMbNyZOeAzdM40sWxwtEcBy+5HuBQ78zGYJ46lsnXPWRjGFUWwDS4wV7vz2YIDzLOlh6Z9XCbuTQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-16T07:55:42Z"
    mac: ENC[AES256_GCM,data:A6my2Btf8MMe9fhpgIiIRdueigUr1pQ/2PR7UewwkjPuiJyjGm/oYm0N30L8pzUjLuf898KpLLsxJSFvUpE1j0gGrFTkJpV51joCg+3hPSwoLa5S2sRZ21iO1ZaPe6kdmhRYFKMaX9ciCZ0xy5QRQckV5oQymE5mQkJMKYCPMzw=,iv:KmpSVLNHZWqtqkP6xUndWUDs0IJAOD7/mi9SFJ8Bmho=,tag:zzn/lFAZRzoATbVbDwC1lg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
