secrets:
    ethereum:
        worker_account_mnemonic: ENC[AES256_GCM,data:WizQDtDDguz8IxDPPGlHyeo1utUXzFXE1NRZ+3yASgKnUoTTD9BpzvWxG9Sr68dCLOXvJjkZsVwIoI8vAXdieX9aKxzRGf+oavG7rdOZubM5uUsusnpbu93FrTpcf3NcnYVbi2akMZ3k69OfEPxvJpvW4HbS/curwVyVYrNkz0V6NPkUQzykiqypV+/1ZBY=,iv:4LyKoDrAC0xhEX8yIBinDV0ILlr7tvYTuIUESgQwvIk=,tag:wihz23uIaxMEenq8XAV+9w==,type:str]
        rpc_url: ENC[AES256_GCM,data:Ojc8MuNysis4dkQaC8woof0gbN/0tHjVWUxKxNzqLrJ2kYsNQFMRSGzSKCI1+4bd+Zr36jydh5ae1K5l,iv:YRhJ+8oRFH/yPVcHAHmuWyic1bm9I9zANgUyODQHMUc=,tag:0diokWO0GdM4c98qu+frUw==,type:str]
        ws_url: ENC[AES256_GCM,data:gyW5Yurdv018wLZ+B61KEvDICRYAcorgHMSR/ZJXhUMdT7JkaknpbopbmAig9+uPQ5uX1UeEYdBzn/oheA==,iv:slvWPd8wNC8WqdPvBhYpwtcfNM8chJYq5jZdh3emkaw=,tag:q2bBwJ4f1x48k+ZZJecCDg==,type:str]
    store_db_uri: ENC[AES256_GCM,data:iRbaN9am8dSZxbAWKC5hOavAJrAfyvK7bOlIDyFmOzpupE14S89JNFQnhKjh3LvegVv/lL4DXC9gR36CRTrVO5L7b0AruyCEwfdD9J4n5OCYz6mP5FlxxCpctbRxHYSpXsxPv09C/XRVps1zkh8uDBzdCBs1gQKndVNBfMhiXGLEfraXD1hMCES8d6i4OV4=,iv:FRzb/H/JmW0w/qqsN5BUlDPqbbapFmnUltteER9R7XE=,tag:eD5al3KBPgU0727Rs0i4+g==,type:str]
    account_db_uri: ENC[AES256_GCM,data:ui3ewj+thIul58+8R5ngHtq5QXu3wKEvOxosbHD2Hk+pErG9OfQ7HkY5ZSVKllyHHCntrlf9CFR8/Q51WdMCLqV8f4a58TH8JhohKxNAAWncBq/SbJsMMQyB7vrLSSqn9nUcbDWuueC8j06xF5WrkAxoNhLRi8yE40WqPCLizCwXkWXSBMJ0aPBRrwI=,iv:6gjDtu8+83Thw0AfJKF1A+W6p7Z4bzo6Si8t3NNcnVM=,tag:Cx3zuJp6dNYEqKtcS62mCw==,type:str]
    opensea_api_key: ""
    bitmarksdk_apikey: ENC[AES256_GCM,data:9qr2EnS+AE+HgZzp4Me9v3PkA/Q=,iv:KH76peHfStGD+auxrWJlHoefTLWrjD/mTU6HzEKj6Ec=,tag:E3HZqGbb6q2nP2Hfd+N9QA==,type:str]
    bitmark_db_uri: ENC[AES256_GCM,data:EMbU4mCNAwDxXh8+/ii1dl1m6kxyiE+yuZt0oyTH2vPS/aO9MleB4c/ZoYekM/fl6VPqMtD5HSkihBweYZnwSvAM/H8waeczGzbPlNYvGeih05v2+JpAkR6DoVbPd6UTB9AhqnXsQJ3Xu5V9tp7pm6I8OWmnpQ/5L8N+NObVy8qy7hIKn+AL5PMKrP1Lf1RGnjAshTSmkLNkYwCJ9ewtilfqRrjkMScmUSPiRSpXzt+6TXY=,iv:viuwGlfnRFC6olBGzuB1tYFW+rQA8IAvemgHoPSZ/ho=,tag:U12HD0Wuyc0SnPZnZOVD7g==,type:str]
    feed_api_token: ENC[AES256_GCM,data:1AuoZ6K1VCpLTH8rc3k+ByuAJFdBT3F7HzjVxShKzxuf+NedaZNtxWFONDRLxGuVNqHaKU1xFvSytavDCq9iU/rO3w5aL13Gt9eeig==,iv:N7PQlZ/VvvZ1EiblJVLzjYaAzmz/1yYeP3nsquqK33E=,tag:8WFXpFZL3/7Xxo4VtY2Gug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/2fc00fb4-6f1c-45b2-a247-41a72fb2006a
          created_at: "2022-11-16T07:56:29Z"
          enc: AQICAHhj5BWgGUcW7rT6Wr8RMMkOteG0zlIjyc3aMstW74cZzgGAfY7APyg0DyDFjw/kHhQpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM84WoJOU8ZVsjK2udAgEQgDv8TGZ9W25f4cvK/PAhX1tkCPV0Oq6KxrvOX+EksKJ3e4xfFXJUZ5Nb28STvAOzpD5CJ7lFMHflObecFw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-16T07:56:29Z"
    mac: ENC[AES256_GCM,data:qUez4Q8JdNaDkQAqiRHHhaYezkQ8ZI1+PKi1nZIyWa+WIP31dqKghdS8LK/MDEq0tWuDdo5vqBUFvIa0QKlsz77eiVUp46XSg5V8Ak7y69oVEHGDq9JibT6HjkhblLZhNV1/ineliJEWV6y2msPtLl5giJU3d6eFV+A7HIru2Xw=,iv:rqIeNS8R5VMWNGdEWv7sAaAFn8aWR9a2YYe1mBlxGes=,tag:zMsBS0UP4JCTj4jhuuhAKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
