secrets:
    ethereum:
        worker_account_mnemonic: ENC[AES256_GCM,data:1N4j6SOG8ovYNQROS41KR2GKLtcpsXtfaUdWphos4PNIckq0r6mivNCi2mOk0bXrsK8jG3nCX96c676RcXe3lbzPYfFlwWxfViMaDrYr6Dfq7GZSQ4Z463x9YdpR+RQPgmu2QINd2141NyDmFae16YnQGBuoeUyvFNjUpptWzsrvcsGkBzL2+ZV754UuBx0=,iv:hVwBae1pzJ0QXcCOksIKedOoBJcG9QdUkoRm29CfxUU=,tag:7i6jQZqxLdRUPt1fxHAzIA==,type:str]
        rpc_url: ENC[AES256_GCM,data:Okq25s7Rg24cf+4J7IAxsYjbgLahzPIkaVkOFpiBu/3HEoMAfcYvFC2QFCVdLo+4M1hS6jUenGyyLn9B,iv:cl1RxVq8lsSZBvftm0Pl1vACyr41+O1W+zSBMj1G9fs=,tag:fiXADRKvTpQ6xGNlhFWooA==,type:str]
        ws_url: ENC[AES256_GCM,data:MGMmJPlNUpU5EunhhvUliQidaa07HEiVnP5a+UTEAk+7FTLJW4+IeEwkB2MhZMZaAxGMZJkUqDdIrSKhLw==,iv:d/fRGvdsstAwmly2KJgd6P2sGmOLXAVk5jHhDZ9YAqc=,tag:NCcpXhenBCFugs5NKq/ZWg==,type:str]
    store_db_uri: ENC[AES256_GCM,data:Q26U0OKpc+MZKtiwwHc2siHUDbf0cNViH0wooq37Z6klaS0FrIExxfQ79xjGgOonjMqse2Sft0y3cgE3ybMJrejexyRi/PLFc6IrQeOTOXy+IrlIj8aWsbQxivdC1IG87THT8YBBKSLLXJFiq/KsSrrH1PErQxztsIwtHipopAk=,iv:7Jp1vBF06turiXwVJAgFsDN3feQlWRMr+6FMJxcmM4g=,tag:7X7Is1Nuavn14KXThC5Ppg==,type:str]
    account_db_uri: ENC[AES256_GCM,data:OrO/e8GsB4ISgPV+Zaci6C5YroSfIO3vzcZ0ho13Pi8LgguxpNNdaZcJClO1ZGFJhOqhI164zDiQWd1TOTVf51oCgL4hgVs2sPpZigR26wZEyil9KZ5qOOnwDm2DVN6gruUPMOf/5PE+mHOJPH279qA/NfKVrWioMlVcB5oVLniOH5NR4HfetrbgYF0=,iv:ag+2rJVKgkXEj/79nYh3EVddLRAqBxsW1ahibWkK0sg=,tag:r1wMkCquRKQqjWFpQCJ/HQ==,type:str]
    opensea_api_key: ""
    bitmarksdk_apikey: ENC[AES256_GCM,data:KdoHSRYQrBTuVThPz8h9/NGXAuI=,iv:3mU+IPzBK9lgKUCFwQm45GMO+iNaJEvC/F8mscIYBKc=,tag:8HEGwm1hip/i6nH0BXKSug==,type:str]
    bitmark_db_uri: ENC[AES256_GCM,data:DYXEBBcjW9jl13VMMe+qY21KZ+5Rj3m4sNlkjCH16qLI4TcC/kZYQ/x/bCKY33bjEn9WrWJS/URaV8BjHI5DL3UY7IdJH+jRa/jDgfv17ONWYqx3PoMxEDp83brWrKaQ38g5huZNSkOTPN3/pUcTn4kzDZrmb+eQBr2meIgrSgieUIRN8/PeRkTiLnf/MMxkUH3RZHrkHZiQjeV0Z75/jOyBMP7hfqoC02UBKG1byGezgEY=,iv:8dfxlyaibfgTZqXmihtf0cjWSZbQHTwzJ+Y9TU8Zzms=,tag:RkkR0xFOEENcJUK1udZjEQ==,type:str]
    feed_api_token: ENC[AES256_GCM,data:jhcrToyzyYcVhydnb161CE7t+c4HS590Z63y9ylZrM/wLRhr43QH/XixemIQ4OmUoinA2AAc5uYMbJedCt8Vxwg8xLcRymL1tW0HqA==,iv:5y/JVTphst5O4kqGKDLwEskZdHJwn9N0Yfg7Rr89M2s=,tag:yiels9SLIu8xsTM4vWB6Ow==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/2fc00fb4-6f1c-45b2-a247-41a72fb2006a
          created_at: "2022-10-11T08:28:12Z"
          enc: AQICAHhj5BWgGUcW7rT6Wr8RMMkOteG0zlIjyc3aMstW74cZzgFmlX69lBJukv4HtQbAKdzXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7eGF2X7JDGiMh1WJAgEQgDvy4iV1+2j4YVqAp4ufmBKnZK6trdpyRbXJ2MCTo6jMihhiJshk67eazIiZesrVbVptcyk4fCfCC5OGVQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T08:28:12Z"
    mac: ENC[AES256_GCM,data:vXbBwlXEo72qKeX3pwttEZFyR9+1R3O/PdMWTuRXoIY8q5DLdOZhAQcTzJle5Sp9QChhkWqIXNb534b32/2AmpVtHdwYmVn2A3gHv1tjy/FcklBcD4nyl0ncJYDFQdgFKzqFL4paAqh53/1i2Nl8FNjrUEES3gBoiCBqtCZdqXc=,iv:4P3LTMI/Im9zvouiWgzdI0aPYad71aP3B8FKw4UhzLc=,tag:nJN/yaPTLpLtprR6+QuRfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
