// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.3
// source: event-processor.proto

package processor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Blockchain string                 `protobuf:"bytes,2,opt,name=Blockchain,proto3" json:"Blockchain,omitempty"`
	Contract   string                 `protobuf:"bytes,3,opt,name=Contract,proto3" json:"Contract,omitempty"`
	From       string                 `protobuf:"bytes,4,opt,name=From,proto3" json:"From,omitempty"`
	To         string                 `protobuf:"bytes,5,opt,name=To,proto3" json:"To,omitempty"`
	TokenID    string                 `protobuf:"bytes,6,opt,name=TokenID,proto3" json:"TokenID,omitempty"`
	TXID       string                 `protobuf:"bytes,7,opt,name=TXID,proto3" json:"TXID,omitempty"`
	TXTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=TXTime,proto3" json:"TXTime,omitempty"`
	EventIndex uint64                 `protobuf:"varint,9,opt,name=EventIndex,proto3" json:"EventIndex,omitempty"`
}

func (x *EventInput) Reset() {
	*x = EventInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInput) ProtoMessage() {}

func (x *EventInput) ProtoReflect() protoreflect.Message {
	mi := &file_event_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInput.ProtoReflect.Descriptor instead.
func (*EventInput) Descriptor() ([]byte, []int) {
	return file_event_processor_proto_rawDescGZIP(), []int{0}
}

func (x *EventInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventInput) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *EventInput) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *EventInput) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EventInput) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EventInput) GetTokenID() string {
	if x != nil {
		return x.TokenID
	}
	return ""
}

func (x *EventInput) GetTXID() string {
	if x != nil {
		return x.TXID
	}
	return ""
}

func (x *EventInput) GetTXTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TXTime
	}
	return nil
}

func (x *EventInput) GetEventIndex() uint64 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

type EventOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *EventOutput) Reset() {
	*x = EventOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOutput) ProtoMessage() {}

func (x *EventOutput) ProtoReflect() protoreflect.Message {
	mi := &file_event_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOutput.ProtoReflect.Descriptor instead.
func (*EventOutput) Descriptor() ([]byte, []int) {
	return file_event_processor_proto_rawDescGZIP(), []int{1}
}

func (x *EventOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EventOutput) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_event_processor_proto protoreflect.FileDescriptor

var file_event_processor_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x02, 0x0a, 0x0a, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x58, 0x49, 0x44, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x58, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x06, 0x54, 0x58, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x54, 0x58, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3d, 0x0a,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x38, 0x0a, 0x0e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x26,
	0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_event_processor_proto_rawDescOnce sync.Once
	file_event_processor_proto_rawDescData = file_event_processor_proto_rawDesc
)

func file_event_processor_proto_rawDescGZIP() []byte {
	file_event_processor_proto_rawDescOnce.Do(func() {
		file_event_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_processor_proto_rawDescData)
	})
	return file_event_processor_proto_rawDescData
}

var file_event_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_processor_proto_goTypes = []interface{}{
	(*EventInput)(nil),            // 0: EventInput
	(*EventOutput)(nil),           // 1: EventOutput
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_event_processor_proto_depIdxs = []int32{
	2, // 0: EventInput.TXTime:type_name -> google.protobuf.Timestamp
	0, // 1: EventProcessor.PushEvent:input_type -> EventInput
	1, // 2: EventProcessor.PushEvent:output_type -> EventOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_processor_proto_init() }
func file_event_processor_proto_init() {
	if File_event_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_processor_proto_goTypes,
		DependencyIndexes: file_event_processor_proto_depIdxs,
		MessageInfos:      file_event_processor_proto_msgTypes,
	}.Build()
	File_event_processor_proto = out.File
	file_event_processor_proto_rawDesc = nil
	file_event_processor_proto_goTypes = nil
	file_event_processor_proto_depIdxs = nil
}
