replicaCount: 1

image:
  tags:
    eventProcessor: "event-processor-0.1.0-2"
    ethereumEmitter: "ethereum-emitter-0.1.0-2"
    bitmarkEmitter: "bitmark-emitter-0.1.0-2"

serviceConfig:
  tezosNodeRPCURL: https://rpc.lima.tzstats.com
  contractBoostUrl: "https://api.limanet.tzkt.io/"
  environment: development
  network:
    tezos: testnet
    ethereum: testnet
    bitmark: testnet
