secrets:
    store_db_uri: ENC[AES256_GCM,data:lZyCmdJjlcyTz6zPQ9WcmiLpXBgHa3QtaFAc+FiSIm5p9wlWVL9hg736IzMhEB5fQZJTyfVOLKup7gr/YWwciwry5mWNWufn6SsA5AxzyKLDQh+2Onzo7R3dTMaKISU+BY773muJuXeSywWOwTXHYLQ65zfDvgsFg4++F9qCC58=,iv:r0MQi0SJkvPty8KwRhBso6heLRLJ/nFsaxqBh4HgF14=,tag:0uGbVpIGDpN5UBZidxwfGA==,type:str]
    image_db_dsn: ENC[AES256_GCM,data:HPJKE0r1MEkOALM6F2K7KZ29j5Js6zh+0ko7EzWLv7m1/E2eIfXd4H5oV3J57pzHC0eVsuGfy1158P1TehjJHNGi5azAIxgax6lNxZT6hQH1wufL7LSns7NsAaskkcr0Ca0nV/kH1nhydtl0h7hwUPaArER8DDWCqYbfHDlLSU5o3OeUuRmwvYwWtJRpCdRvQK0dHyv3Ml8JeqBzptW53LYOx80PnnFVGV/Nv08G,iv:CV4LvSRQYpXafV/BARpTOMD4AOnUvtagQkhtRwPFa98=,tag:ARh2LjixCk236BnM3zjKBg==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:wJyoJmMaFfEpDoqjQmsmJ6lgzREM6TQBmZB/Duloxo0=,iv:oq2G6mvBuHfDVgPBz8UwYJrO+H1RSB7QknlgZn0np4M=,tag:UIq8DKftbRBNBfGbuAneIw==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:SKhVdaNBAo+uf8E+Ema+zlzh8SYkzysIDK9pXOhmcoHg5+APA3LeNw==,iv:0supr803GpP5eKJgn2ojrg/3FaUeu+HlZNfB1RXNrs0=,tag:38mgB4Qsdv4kP/OsoyUuGg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/1965b82b-4f9b-4c0d-9dfa-d575132528d3
          created_at: "2022-06-17T04:25:19Z"
          enc: AQICAHi/zaXXtoouOl3wGZO6fSpK7NYlac8Ro+bHbPaUjUK5fQGId5/dCzWytoBPsT5jUZzEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYS3pu/YK8G+bBkhxAgEQgDtGNgoWkw7Q0eilzYF7uoWaehs5iwNM/JrId7B4CUfJZ8uNYlTm2Pn02MRwA9iMDsNzl+Y1zKuzhQQAyg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-17T04:25:19Z"
    mac: ENC[AES256_GCM,data:axgnA5FipM7uDAQljGnCdy8mnIAKSJA5cOklcDFjXePjQXh0Y16BiRSb+BC2H3LXTH6+5YLAKBLPUfNpIAD3MNHc7SRot3IXD0tUzECj3rkN9pNxur2kSNvGIRxgYbesWLn9mIyR8FUw60PRxjF6tiQFSFAXH61Pn8JWbxHwd8E=,iv:/YeR5mhCTeFXRAxiqYxs1GPOkIPRuBMkesAQF2eWcqQ=,tag:L63ntY6KGXnswAUPcICxtA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
