secrets:
    store_db_uri: ENC[AES256_GCM,data:i8E64sSYIy2+xgl84Dqc3enG4mrxkvdu+aYmLGmU4m+hhI89X8a/zuy27ljNZcvo+4ou6p613N/7ENfXg/uXgZTPHoJ88i9WpUW/ZorqOSuQF9UyDfqkbHNBe8ccr5YqNndtQmKQcDhENiqTaez/Mg5Mo6K+n7/r/9jQwdBq/OI=,iv:1N1n3mEl3O2ty5OJlFxVFr7TcohQHPo2j7iSNceeB6g=,tag:ay7HoPcW0ISemlx/RkeJWA==,type:str]
    image_db_dsn: ENC[AES256_GCM,data:oRS4VI5YVTzH+DgCeQxIeeTbe/rVqDLMwfwqCuWzFFgp3egC8FTBGXmgdb2xekMADquM51/ZlS10DsfLopi3P5Ly107mcGYHnsDb6aFKOO0IFEk2RWR4a7Hq33aaRW/6MftlmjqNpUqTbeNN4UQrQbRn+MIR9sm3ndbWx5Cmyk9I2vizRIfIOJepK2bct7eSjgZL1GRHyrIGpnpkieQwkXG3iRTaMvXFWb7SSJ/D,iv:OhBVFPB9wkaGAyanOGs3n+/qSIe4ObxmbfrIaFMFl9s=,tag:x4gr/C6If1S475jxaQmMvw==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:lICGsmmfvd93emlCr4isZFU6a/MxlNCf77F4OmjriMI=,iv:2WlfLusB1viYbdPLfAy59g76G0hk6ZkQjHCxIQUa04U=,tag:858BmztGW1hxPhbVaGPtWA==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:78M2yxZTiANGLggAPCna1RAYlzsmvtdRK36zNHBXAXEtBl1+TqeNYg==,iv:CX0lmnRreg/Bm+W497vS9sVIbWr67Iuf7BPhNG5hTaw=,tag:yT6UwCko3wjA16DbE+QyVw==,type:str]
    pinata_jwt: null
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/1965b82b-4f9b-4c0d-9dfa-d575132528d3
          created_at: "2022-09-20T09:31:51Z"
          enc: AQICAHi/zaXXtoouOl3wGZO6fSpK7NYlac8Ro+bHbPaUjUK5fQHHvtuNEqF6LyQ9/4KY3KeeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI1nKnBR0ztlSIvscAgEQgDvcbvW7mMIRvbpvxLCHe7aBEpVz7rslHHPld2ZthVpdp9pP/IFFcBLUZ4+TDA7iTgYUch285DHHbLHEFg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-20T09:31:51Z"
    mac: ENC[AES256_GCM,data:ESwxIigacsxOKmk2TIdtpKcJGDuJQceHxulp32UMpKvnIg3kkyi/kBE/pambxqfyOFnLVgS8VXL4IPShsqQa0wh9FvnW6rMRrSurxNibFC93ZY1kv1kKxpJAt9H80PFqztZdQsro2UsEUFetdj+Zcz90rqVYSQEaCMfaXRq/9L0=,iv:5d4BoCsDRculdhWZ8s1hWe9cUUwdCc8mvvfO9rfbBbs=,tag:DX60BbNubtO56rwWiqs1hQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
