replicaCount: 1

image:
  tags:
    tezosMarketplaceIndexer: tezos-marketplace-indexer-2.7.1
    tezosPostcardIndexer: tezos-postcard-indexer-2.7.1-4
    tezosFeralfileIndexer: tezos-feralfile-indexer-2.7.1-1

serviceConfig:
  tezosNodeRPCURL: https://mainnet-tezos.autonomy.io
  contractAddresses: [
    "KT1QWATcHYpBVDxvNoxw5CbkaMGpjm4SxXa2",
  ]
  postcardAddresses: [
    "KT1Lak6VLc3k33EqvpTBfpXspoRAKUa4ycVJ"
  ]
  eventProcessorURI: nft-event-processor.autonomy-staging.svc.cluster.local:8765
  environment: staging
  network:
    tezos: livenet
    ethereum: livenet
    bitmark: livenet
