secrets:
    ethereum:
        worker_account_mnemonic: ENC[AES256_GCM,data:VQZX0EURR9mmHAtNqQ5DDYM7nlMSMFG+OPIuld7I6iKlWEz45xD50W8zLovQr9M8cFzlkbC6C/d2dvrV/qFEJNsQdNbTZ8wb6ABR3EbBmIaiQWZE8CKCY9xV4etxWJzl31Tq2zA1UiQN2yC53tNNC9ga94P1jcBq4WWv7sbS9CVtieOSW8zqeNMbhSz8OcI=,iv:CQWhMSUt4YFO61LJ3flRoNhFd+z+HzjBnJFLzciBIAw=,tag:wOXjoh+7NRjJT36gHNs9PQ==,type:str]
        rpc_url: ENC[AES256_GCM,data:D6nhu/mnGKugJiR+ASlabLfRP2TWky+Qoz930slqJK6WwKRrEqU1Ol3RmCcDLIl8Nw1NXxfzkZ6i/FBIYQ==,iv:CWECa4DsZFHwrc3bHPuQquSO0V98vDNU1U5wj2jY7kw=,tag:ZSLYv7cmN7AbTu+2C+0ztw==,type:str]
        ws_url: ENC[AES256_GCM,data:pJ/YHiw81XixUUvogW7Ua1AA2yRiuFxKXWMyzY584xP8QjaN0bC+YAKkjiF+nrEKD9b3RdcaUh54CAfDi9w=,iv:WO0CUl1Q7KKMGDQ93BNVag9FpWxNeGHeK5H622uDifg=,tag:6GVmjmmJCjMUJGmuMTU+YQ==,type:str]
    store_db_uri: ENC[AES256_GCM,data:K49YKDE1SYEwSh6YkP57PxBTB19Ge1XUdkTLLv7GUHU5dMP0VCeRhRyzqFw/51Sk9IfyzHB6fc6NDRqKWsLaF8FTEkR3YlG9AF9sC7UqhCMVPE/OAb79ZjhI4EixUXoR9vMrWV2BWhOK4bXeJ6NHeRfaDU2bbd8zelxuPpcfZWU=,iv:MjfydzU0OOSK4RF/7rrTKdStIk7My4X75OaVbRf7NDY=,tag:eXxkSqxovCNYXVgPvnadbg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/1965b82b-4f9b-4c0d-9dfa-d575132528d3
          created_at: "2022-03-25T08:36:06Z"
          enc: AQICAHi/zaXXtoouOl3wGZO6fSpK7NYlac8Ro+bHbPaUjUK5fQG+WG77I4XafiGAtSuy5x4RAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGdDnAVKx7lIIG06vAgEQgDuE70rWrSXtNYVaxMBnbkeU/0dd8R4b9weQ8egLj4q8ZjONl82/i9fw5d2cAss87nGyV8dtX4X1J/6dPw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T08:36:10Z"
    mac: ENC[AES256_GCM,data:pwd6w3nEUHeRp3gdFBBECSRqxdSLYICWsGaeN0NiTxCO650h0vyH2tGCIMvg4dCSSi9g5Vx+yxriP0XCdKSPDZGb2aS1sVNoe1lsTc8AORcvmo7nEH0IfFHj1ocn+Gf+VGcVxY5LbpFaogfb3koPGGLzW1PVXcbUD2NplJ2qMGM=,iv:iVBGFEUHafruDBEDBtOY3O3+iArn5SNMDLmy0xImuW4=,tag:EPaW6ugT9ua/Ay18SRzE5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
