replicaCount: 1

image:
  tags:
    eventSubscriber: "event-subscriber-0.0.16-5"
    tezosMarketplaceIndexer: tezos-marketplace-indexer-0.0.1-4
    tezosFeralfileIndexer: tezos-feralfile-indexer-0.0.1-9
serviceConfig:
  tezosNodeRPCURL: https://rpc.kathmandu.tzstats.com
  contractAddress: [
    "KT1Ca3Bpug7mZaQ2YQvVYzu4Byx7V28nNrat",
  ]
  # tezosNodeRPCURL: https://rpc.ghost.tzstats.com
  # contractAddress: [
  #   "KT1VLvci96uGUNtCP5TYJFNGRKUkbgfs684v",
  #   "KT1HaKfv73deHy4x5k4DUtL3CtkX5cVpFZUf",
  #   "KT1QZJ9qJ4RAxmMrjLaBQAUTMvJQAMshBkJr",
  #   "KT1RHWH2KYVHaP5Dxvkr2gx75Zks7PWvQEu2"
  # ]
  environment: development
  network:
    tezos: testnet
    ethereum: testnet
    bitmark: testnet
