secrets:
    store_db_uri: ENC[AES256_GCM,data:uWTuojPIKywLSopUtbuVxs1MtfGfQVNp8SOBkqc/1zQcUGcP+Y9J0KRyd0nNc9DVxbZTvEMPxXDN8G/MMJLhdgrDhzI0oeB1OPp3jSo3599q81PXpnLLILNO6+iiExthTwNsWjvey+2CFFH3yUpTdqLJg2tZ6b5qfwcQIKiKDlQ=,iv:phFDv656W9EtMbMTrDLYjYdU1A/jssY93Uw3QtL8C/o=,tag:gq14f6QmZ7ZYyBVRYj/SPg==,type:str]
    image_db_dsn: ENC[AES256_GCM,data:H00/KZrt/2nEPvZIxEBK232Xcy4LRjTbGu1pbghoRyX44dPYtNvUHRC9P/Aygo61EdnxFb8aDUpLTv3SJHBOGcNvlp13pwW7sJfDP/2uKJI3zwgiRmW11lU0lbviMdumdajDXGeCtxaLElYnnA4hwh4oUXjtscCLoy3wcoNSh007Ve94wP+xQjV3Tk0XPcfsGsb9XafW77oc4b9LRbhITt2CPJaI2VODjR6DYCTA,iv:zkNXINYc8D9l1DwGIeVLxGs9b8DGegIwpL5H4jNWShA=,tag:Dd7iLOohUC+BiEMx6QSZkw==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:9N12kStOYT4hNyfcCmGfDq2GQbDm12oCb/o76TV80Zg=,iv:kRRxy8kEFoUwtOpvoA9dYyEaAd265HqOZ4boQ+tf8TQ=,tag:lTqsF3gRaPWdCXXtYh7+vQ==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:rpcqnPq+a8WxTHLWbzDqsGlucRmousYwBWqcQq+wYZv6bInH8vj62g==,iv:X0lVDnSmKEMkCEGJs7cqFSJS0Efo8EOzWrBVFNIoXws=,tag:0rd+x9dOPQ7AINjDAZ+rVg==,type:str]
    pinata_jwt: ""
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/2fc00fb4-6f1c-45b2-a247-41a72fb2006a
          created_at: "2022-10-11T08:40:54Z"
          enc: AQICAHhj5BWgGUcW7rT6Wr8RMMkOteG0zlIjyc3aMstW74cZzgELL1NcHE/1h/OGoq1MtLczAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM53YEQ0TzZbt60s7nAgEQgDuGo3tcOm70g3KooLdlandAoRlogfUjjEbsq50j94CCo2/F9Amz/oyHKVBop5UvHwBCYDPBRGNfTkJfAQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-11T08:40:55Z"
    mac: ENC[AES256_GCM,data:4xu3XziU35WGCzM8xi/wh1ozLs+7oftXdo7vFYIs15NbDdQOJyLTxyIuVl5MZTxjsaGXNDimV2Ausew0nCsdU8yo20PSvjRNd4vPXqIgcu5Uow3wFupPXJ3qzxnVYNz0x9gsIjycYSxfwDhYJRGZcRP4HtiWk4rX3at0thd4MFo=,iv:SCjOqVPe8QwL9giyMmlPgmUTl1/YRbZx0PCeBPBrhCU=,tag:7hzj9lF6hqR9Wmouz4tLUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
