replicaCount: 1

image:
  tag: "image-indexer-0.0.123"

serviceConfig:
  logLevel: "info"

  # 1 = Silent
  # 2 = Error
  # 3 = Warn
  # 4 = Info
  dbLogLevel: 2

  cachePeriod: "144h"
  cacheRetryInterval: "24h"
  cloudflareUrlPrefix: https://imagedelivery.net/zDrO-YmKDy1tz0_bjCkDJg/