# Default values for nft-indexer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 083397868157.dkr.ecr.ap-northeast-1.amazonaws.com/nft-indexer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tags:
    api: "api-0.0.2"
    background: "background-0.0.2-1"
    provenance_indexer: "nft-provenance-indexer-0.0.16-4"

serviceConfig:
  cadence_hostport: cadence-frontend.cadence.svc.cluster.local:7933
  cadence_domain: nft-indexer
  feralfile_api_url: https://feralfile2.dev.bitmark.com
  opensea_ratelimit: 1
  environment: development
  network:
    tezos: testnet
    ethereum: testnet
    bitmark: testnet

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: true
  external_dns: true
  hosts:
    - host: nft-indexer.test.bitmark.com
      issuerRef:
        name: letsencrypt-dns
        kind: ClusterIssuer
      paths:
        - "/"
    - host: indexer.test.autonomy.io
      issuerRef:
        name: letsencrypt-aws-dns
        kind: ClusterIssuer
      paths:
        - "/"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=10886400; includeSubDomains; preload";

certificate:
  enabled: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
