apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-indexer.fullname" . }}
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
data:
  config.yaml: |
    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

    server:
      port: :8089
      grpc_network: tcp
      grpc_port: 8888

    jwt:
      public_key_name: {{ .Values.serviceConfig.jwt_public_key_name }}

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: {{ .Values.serviceConfig.cadence_domain }}
      log_level: 0

    fxhash:
      api_endpoint: https://api.fxhash.xyz/graphql

    objkt:
      api_endpoint: https://data.objkt.com/v3/graphql

    opensea:
      ratelimit: {{ .Values.serviceConfig.opensea_ratelimit }}

    tezos:
      domain_api_url: https://api.tezos.domains/graphql

    feralfile:
      api_url: {{ .Values.serviceConfig.feralfile_api_url }}

    ipfs:
      preferred_gateways:
      - nftstorage.link
      - ipfs.nftstorage.link
      - ipfs.bitmark.com
      - ipfs.test.bitmark.com
      - ipfs.io
      minter_gateways: |
      {{- .Values.serviceConfig.minter_gateways | toYaml | nindent 8 }}

  background.yaml: |
    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    fxhash:
      api_endpoint: https://api.fxhash.xyz/graphql

    objkt:
      api_endpoint: https://data.objkt.com/v3/graphql

    opensea:
      ratelimit: {{ .Values.serviceConfig.opensea_ratelimit }}

    cache:
      bucket_name: {{ .Values.serviceConfig.cache_bucket_name }}

    asset_server:
      server_url: {{ .Values.serviceConfig.asset_server.server_url }}

    ipfs:
      preferred_gateways:
      - nftstorage.link
      - ipfs.nftstorage.link
      - ipfs.bitmark.com
      - ipfs.test.bitmark.com
      - ipfs.io
      minter_gateways: |
      {{- .Values.serviceConfig.minter_gateways | toYaml | nindent 8 }}
