apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-indexer.fullname" . }}
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
data:
  config.yaml: |
    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

    server:
      port: :8089

    jwt:
      pubkeyfile: /usr/share/nft-indexer/jwt-pubkey.pem

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: {{ .Values.serviceConfig.cadence_domain }}
      log_level: 0

    fxhash:
      api_endpoint: https://api.fxhash.xyz/graphql

    objkt:
      api_endpoint: https://data.objkt.com/v3/graphql

    opensea:
      ratelimit: {{ .Values.serviceConfig.opensea_ratelimit }}

    tezos:
      domain_api_url: https://api.tezos.domains/graphql

    feralfile:
      api_url: {{ .Values.serviceConfig.feralfile_api_url }}

  background.yaml: |
    log:
      level: {{ .Values.serviceConfig.logLevel | default "info" }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    fxhash:
      api_endpoint: https://api.fxhash.xyz/graphql

    objkt:
      api_endpoint: https://data.objkt.com/v3/graphql

    opensea:
      ratelimit: {{ .Values.serviceConfig.opensea_ratelimit }}

    aws:
      region: ap-northeast-1

    cache:
      bucket_name: {{ .Values.serviceConfig.cache_bucket_name }}
