apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nft-indexer.fullname" . }}
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.api }}
  selector:
    matchLabels:
      {{- include "nft-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nft-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.api }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /nft-indexer
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
          env:
            - name: AWS_REGION
              value: ap-northeast-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_secret_access_key
            - name: NFT_INDEXER_STORE_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_uri
            - name: NFT_INDEXER_STORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_name
            - name: NFT_INDEXER_SERVER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: server_api_token
            - name: NFT_INDEXER_SERVER_ADMIN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: server_admin_api_token
            - name: NFT_INDEXER_SERVER_SECRET_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: server_secret_symmetric_key
            - name: NFT_INDEXER_ENS_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ens_rpc_url
            - name: NFT_INDEXER_OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: opensea_api_key
            - name: NFT_INDEXER_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: sentry_dsn
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: "/.config"
            readOnly: true
          - name: jwt-pubkey-file
            mountPath: /usr/share/nft-indexer
            readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          name: {{ include "nft-indexer.fullname" . }}
          items:
          - key: "config.yaml"
            path: "config.yaml"
      - name: jwt-pubkey-file
        secret:
          secretName: {{ include "nft-indexer.fullname" . }}-jwt
          items:
            - key: jwt-pubkey.pem
              path: jwt-pubkey.pem
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nft-indexer.fullname" . }}-indexer-background
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.background }}
  selector:
    matchLabels:
      {{- include "nft-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nft-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.background }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /nft-indexer-background
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_secret_access_key
            - name: NFT_INDEXER_STORE_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_uri
            - name: NFT_INDEXER_STORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_name
            - name: NFT_INDEXER_ETHEREUM_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_rpc_url
            - name: NFT_INDEXER_ETHEREUM_WORKER_ACCOUNT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_worker_account_mnemonic
            - name: NFT_INDEXER_ETHEREUM_INFURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_infura_api_key
            - name: NFT_INDEXER_ETHEREUM_INFURA_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_infura_api_key_secret
            - name: NFT_INDEXER_OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: opensea_api_key
            - name: NFT_INDEXER_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: sentry_dsn
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: "/.config"
            readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          name: {{ include "nft-indexer.fullname" . }}
          items:
          - key: "background.yaml"
            path: "config.yaml"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nft-indexer.fullname" . }}-provenance-indexer
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.provenance_indexer }}
  selector:
    matchLabels:
      {{- include "nft-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nft-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.provenance_indexer }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /nft-provenance-indexer
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_secret_access_key
            - name: NFT_INDEXER_STORE_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_uri
            - name: NFT_INDEXER_STORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_name
            - name: NFT_INDEXER_ETHEREUM_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_rpc_url
            - name: NFT_INDEXER_ETHEREUM_WORKER_ACCOUNT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_worker_account_mnemonic
            - name: NFT_INDEXER_OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: opensea_api_key
            - name: NFT_INDEXER_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: sentry_dsn
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: "/.config"
            readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          name: {{ include "nft-indexer.fullname" . }}
          items:
          - key: "background.yaml"
            path: "config.yaml"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nft-indexer.fullname" . }}-account-token-indexer
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.account_token_indexer }}
  selector:
    matchLabels:
      {{- include "nft-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nft-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.account_token_indexer }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /nft-account-token-indexer
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: aws_secret_access_key
            - name: NFT_INDEXER_STORE_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_uri
            - name: NFT_INDEXER_STORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: store_db_name
            - name: NFT_INDEXER_ETHEREUM_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_rpc_url
            - name: NFT_INDEXER_ETHEREUM_WORKER_ACCOUNT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_worker_account_mnemonic
            - name: NFT_INDEXER_ETHEREUM_INFURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_infura_api_key
            - name: NFT_INDEXER_ETHEREUM_INFURA_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: ethereum_infura_api_key_secret
            - name: NFT_INDEXER_OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: opensea_api_key
            - name: NFT_INDEXER_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "nft-indexer.fullname" . }}
                  key: sentry_dsn
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: "/.config"
            readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          name: {{ include "nft-indexer.fullname" . }}
          items:
          - key: "background.yaml"
            path: "config.yaml"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
