apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-subscriber.fullname" . }}
  labels:
    {{- include "nft-event-subscriber.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: :8089
    log:
      level: {{ .Values.serviceConfig.log_level | default "info" }}

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    notification:
      endpoint: http://autonomy-notification.autonomy.svc.cluster.local:80

    store:
      db_name: nft_indexer

    feed:
      endpoint: {{ .Values.serviceConfig.feedEndpoint }}

  ff_indexer_config.json: |
    {
      "contractAddress": {{ .Values.serviceConfig.contractAddress | toJson }}
    }
