# Prepare files and a temp image to build.
FROM node:16-alpine3.16 AS builder

RUN apk add git
RUN npm install -g npm@9.5.1

COPY package.json dappetizer.config.ts tsconfig.json /app/
COPY src /app/src

# Build the app.
WORKDIR /app
RUN npm install && npm run build

# Publish files to a final image.
FROM node:16-alpine3.16
RUN apk add curl jq

RUN apk --no-cache add python3 py3-pip
RUN pip3 install --upgrade pip \
  && pip3 install --no-cache-dir awscli

COPY --from=builder /app/package.json /app/dappetizer.config.ts /app/
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

COPY entrypoint.sh /app

COPY dappetizer.default.config.json /.config/

# Run the app.
WORKDIR /app
CMD ["./entrypoint.sh"]
