apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-processor.fullname" . }}
  labels:
    {{- include "nft-event-processor.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      network: tcp
      address: 0.0.0.0:8765

    store:
      dsn:
      cache_expiry: 24h
      log_level: 1



    check_interval: {{ .Values.serviceConfig.check_interval }}

    log:
      level: debug

    debug: {{ .Values.serviceConfig.debug }}

    sentry:
      dsn:

    indexer_grpc:
      endpoint: {{ .Values.serviceConfig.indexer_grpc.endpoint }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    feed:
      endpoint: {{ .Values.serviceConfig.feedEndpoint }}
      api_token:
      debug: true

    account:
      db_uri:

    notification:
      endpoint: {{ .Values.serviceConfig.notificationEndpoint }}

  ethereum.yaml: |
    ethereum:
      ws_url:
      lastBlockKeyName: {{ .Values.serviceConfig.lastBlockKeyName }}

    cache_store:
      db_uri:
      db_name: cache

    log:
      level: debug

    event_processor_server:
      network: tcp
      address: {{ .Values.serviceConfig.eventProcessorEndpoint }}
