apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-processor.fullname" . }}
  labels:
    {{- include "nft-event-processor.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: :8089
    log:
      level: {{ .Values.serviceConfig.log_level | default "info" }}

    environment: {{ .Values.serviceConfig.environment }}
    network:
      bitmark: {{ .Values.serviceConfig.network.bitmark }}
      ethereum: {{ .Values.serviceConfig.network.ethereum }}
      tezos: {{ .Values.serviceConfig.network.tezos }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    notification:
      endpoint: http://autonomy-notification.autonomy.svc.cluster.local:80

    feed:
      endpoint: {{ .Values.serviceConfig.feedEndpoint }}

  dappetizer.feralfile.config.json: |
    {
      "indexing": {
        "fromBlockLevel": 2845033,
        "contractBoost": {
          "type": "tzkt",
          "apiUrl": "{{ .Values.serviceConfig.contractBoostUrl }}"
        },
        "contracts": [
          {
            "name": "FeralFileV1",
            "addresses": {{ .Values.serviceConfig.contractAddresses | toJson }}
          }
        ]
      },
      "tezosNode": {
        "url": "https://mainnet-tezos.autonomy.io"
      }
    }
  dappetizer.marketplace.config.json: |
    {
      "indexing": {
        "fromBlockLevel": 2845173,
        "contractBoost": {
          "type": "tzkt"
        },
        "contracts": [
          {
            "name": "fxhash",
            "addresses": [
              "KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE"
            ]
          },
          {
            "name": "hicetniuc",
            "addresses": [
              "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
            ]
          },
          {
            "name": "versum",
            "addresses": [
              "KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW"
            ]
          },
          {
            "name": "fxhashv2",
            "addresses": [
              "KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi"
            ]
          }
        ]
      },
      "tezosNode": {
        "url": "https://mainnet-tezos.autonomy.io"
      }
    }
