apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-processor.fullname" . }}
  labels:
    {{- include "nft-event-processor.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      network: tcp
      address: 0.0.0.0:8765
      
    store:
      dsn:
      cache_expiry: 24h
      log_level: 1
    
    log:
      level: debug
    
    sentry:
      dsn:
    
    indexer_store:
      db_uri:
      db_name:
    
    cadence:
      host_port: cadence-frontend.cadence.svc.cluster.local:7933
      domain: nft-indexer
      log_level: 0
    
    feed:
      endpoint: http://autonomy-event-feed.autonomy.svc.cluster.local:80
      api_token:
      debug: true
    
    account:
      db_uri:
    
    notification:
      endpoint: http://autonomy-notification.autonomy.svc.cluster.local:80

  ethereum.yaml: |
    ethereum:
      ws_url:

    log:
      level: debug

    event_processor_server:
      network: tcp
      address: nft-event-processor.autonomy.svc.cluster.local:8765

  bitmark.yaml: |
    network:
      bitmark: testnet

    bitmark:
      db_uri:

    bitmarksdk:
      apikey:

    log:
      level: debug

    event_processor_server:
      network: tcp
      address: nft-event-processor.autonomy.svc.cluster.local:8765


