secrets:
    store:
        db_uri: ENC[AES256_GCM,data:jBALKDkM3dof1QAs0vbXZ6M4H0WqI6cFicWBRSe1EoJso2aamprzWBV3L7Dv5uJ7nep8xj4v6QjADzOYtTE7fx6kmp1RXes9nK0RmSuMnQ1Woep7Bz+wgLFwk4f2u535n8MdzC3xQ7s=,iv:MnKR7H0zQIYzSj6H9fKaUWDfnBOvtTusLt3sekDaqOU=,tag:mv7AI8tLxRg6Y2Rf79o0Qw==,type:str]
        db_name: ENC[AES256_GCM,data:0MAtpHM/BXNPd8U=,iv:xBWmrN/+kw3jMbs/Y/8geG/7JuE5nLbUBVbvU+it2R8=,tag:6YvlDDYenMIeeuWKY6DWkw==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:puDkNMltgNEH0+W/NMBz061lXsz8WTFJWqhcvTWPO00=,iv:UrLvAzthnRu7ZbPsD9VeMnBNAtPK8o/kfIvaYPi2KD0=,tag:4wSh2XHfxHwk+xTeRU3P9A==,type:str]
        admin_api_token: ENC[AES256_GCM,data:G1bCVRyY/kwF4YzxG7RcqxN6XJFlBvKyFzvhDMUnrvg=,iv:kt2hJBD0I4KczIppzXubi70K+V4hQ5CCahVXTDfqx6Q=,tag:ru9j0xD9w9hLos3t+6c3sA==,type:str]
        secret_symmetric_key: ENC[AES256_GCM,data:M1K/ZOqm0W4tUf2Rc1wPLZn26Zl3QC46t1ugRXbLmYE=,iv:96qQ3sW61RxhDE9HPNgeiVWwfaxmrv4D4ZX1vgQj+Pc=,tag:I8ZkT8H9yvuSBOLKHial3w==,type:str]
    opensea:
        api_key: ENC[AES256_GCM,data:64ONZSyV89bFMaC84ma77r9dM23cicEdxvsOsZ+cvh4=,iv:N75QSzoHfZtQDc/go+AQpUbudNiM/2eC7hl6FihWmtw=,tag:RfIue4v1YyyKkuhFviMfnA==,type:str]
    ethereum:
        rpc_url: ENC[AES256_GCM,data:yHFywzthH7KPsxb5ghSiPD3cHmsElZkIPOH2oUkqq9NT4naXp/u08l0GXjcoWAdlOE7BbMEf9wVlsqaVsg==,iv:Xvhp8SpDepLWYotHYDJuFeZMi4m/2aDhNomNqtrpnQg=,tag:SYWtsyhHsVO4tRJA6FDwHg==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:O8CiUUo22/J/ei5i0YDPskb1TDukgz0P35ZnsANJSiTJncSV9fmdXO62Yp3g+1ky9GtcWqu2Mp3e7cta8zACmvzTREn3QLqTcKBmQ01ska852EbanPlZzD61JouDwrSMXyhIrg6rKM7cqU0hqmqotxxJBYek9PJsB5wll+orbLD3CeRF/Z90KfK5IRMUh60=,iv:TQj70tdLljSV4BinxfKUTTZSgiz9/uZhulYwxrL8xR8=,tag:/QsgNuQiJNaNI39ox8zC7A==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:V8a6O0KpNk0lhfqAHvWFpoM4wRoZKzotdfyxAksoDizw/0HSkleo+veaB3Xi404+o/76FB0BNUinYfmlPw==,iv:XFAWZtNBZWZhg+YjPl6ci5X/lVGxg3mgM0qhgMj5Lm4=,tag:mjNEpdik+lClHp87ovzGLA==,type:str]
    sentry:
        dsn: ""
    aws:
        access_key_id: ENC[AES256_GCM,data:gPA+QA==,iv:opZB28RTV0zK3HlTGUKbPEcgysPcaRVb2j7HAlACfSU=,tag:xahMa/rKU+Yb1t/LTrTerw==,type:str]
        secret_access_key: ENC[AES256_GCM,data:+OtknQ==,iv:3Mj0+p2YUMPhFpocdjNseAOEsvGz7gWfuLSPhw5V7uo=,tag:JKgQlPLRDGKuOOAcH1/G5A==,type:str]
    jwt_pubkey: ENC[AES256_GCM,data:Lri1nn2G2dKxVdZlexcGTehqcGil9n1y13H/JyQA5El402YL3cjR2W6RRtnKbV/aCyHF/nb2wg3/V8F1Qwnq0YDRzWj3s3Ak7eGq/DgJ6JJVFIraIirHNJ9U2wt7kPif6b1mUzHwwq9IamCENewJTOA4hHMCODm8BsIkxJi15I+lqsZZt8Iw/TuZ4K+dEu5BxhPWs7iR/9kMqthRx1z0kbWNBw3H5RQQalKEEm1/CKCoNuT5Oh9enJwKIdVlP6ECpTc3ungEkJmTBdnR8k+Tz+NqfXdEc/MfKAZ1C2Agq0gIwkEN5kRs4zmvKpDRbnGKL2/CKzCrp+G+jaU1aE8+JDoJaKowqcqek7/xCpGj0ccIDEj36KtJuA+y3bY4kv0SEG7Jo2t1Ej2HR99P5MfImv4vWkAW17RPVbJTug2IHCpEsZw4ehJ2O/GOcgy5ktc0/40oQGsz7GbdHpXf78outGmHY7fMz8SmNFZ9lbK41/a+p3jKAbY6SUwL6UgjncjY6II+VRrn+TB/J+MkgOTSQQs14XDEqCqlopjry+izEqBcR8QObjJ1s4QVw5cppGg4j/dkWtD45zmKhdJcuKuzzOIZ8ZH7rEoeR/+qYMUXOiwCir/C4cEeZiyj0kZaD+HfmcGMY36bpfDBJVR82g3HdcwDFD4k29xQUTe+DcWEitH+pQpgy09fTN/QCyXK/6BAGwP7/be+/EENnqws3IsOQzvsOOyvMH6PUZxVuo+jNPv5Ji381Y4cCrZHGjy1BxLNGZdLccbGSwtHJG3S63erRgpdVlzd7OaTpooqqktwubs22T7c9eet6ZzsOgpX/AAl/Bn52juaUomhXsYe81wczXvvr0lAaCKKHrfRx2WdaRZ+Cp+xw9hclAdhciDdTDSaKOyXeh2Z40tTIqDeGD8lhanehOriB7QBjQJBQha4Q629D5I8u7HzSlZaK7kVNtDO2/RBpRPyjl0gWr9Z/kQc9R27nIA3RLLrnBdtnc88kTvYLjY/WaSFFc+7GQkeIul7mwjwvbd5niz7mYWt9SSOr0z8TAahYtm+TTw7nbyct3M=,iv:uLL7r5mPd2RDwLXdvcny0LfWaLg0AKYicGwThDK3Bt4=,tag:x9qIj3DnO8Tn9810Yrgsiw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2023-02-01T10:52:31Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQEISp8vNTuOMtsrWeH5wKhJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMU/A2IddggnbBqVufAgEQgDt/VigoSzOjNJkjI8IWLQH5kPRGkrl62/QrJeh51hQm2mWY8qJkVRKIlf5DytCItJesr1edUS+n24YIdg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-01T10:52:31Z"
    mac: ENC[AES256_GCM,data:FUDdQkJtyVetyir5bGIHw5js7BV361zsejdoKKOTZkL9+LvGToU6+QuPjSE2YMO8veAzQMT2YPRmYp0tmbuhLFA8K3FX45fuP5y7+aD9gC93VKTwvH6tsuKo7b61tPrZBYs3/J2w2HMXsDZI9WMHqrp7pNDZSiodYL9Gnt8xEDc=,iv:uwV/9KDLDszoGh/SUxpkiZF5HMTGwYSunVhTEP9rj0c=,tag:y2Q+mkJ9Ee4qD+IIsL5CNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
