secrets:
    store:
        db_uri: ENC[AES256_GCM,data:6C4SNNCfm46ggHmysQoprj8/yYvemkOK8iaPHxOtIbYwo8xk94t79bmPmdZzfqdP7u5/FYOI0VN8UIdxwYo4rutLqhvG1pFqW+KeneDbeYs0pIAPqJ/Nsmv2i9nTgKCG6UaTfoNXsDI=,iv:7sCaXOvhnkjtiFnZq/BMv/6bOk2HlvaN4RhDRGoU4Ps=,tag:FgLUC984dF52C+6qhTkTsg==,type:str]
        db_name: ENC[AES256_GCM,data:E/aVsi8PiTVzoYU=,iv:UlYcLL77NkA20OB+yFtdLSv8h8AJ24de3r9NEZHooNw=,tag:E+RWs8qKnQGi2xOkNXo64g==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:xgtQq63dJzptJ/HNK1vkZTwbSvX1uc506I5ZnV3rYng=,iv:RBMPWdd1rOQ+4b+9dVb61V+MkGL9XYYe9Y70ogzz7V0=,tag:6ownuvn5F3MEMrCpU6VeuA==,type:str]
        admin_api_token: ENC[AES256_GCM,data:FWRVVV0czzmn9BJ1A3j+8w52sXG4O+Oe6Fs89P9v9fA=,iv:5j4EQSpfuCB4m1DPFascpSv6IrnfYulz8Dw91PmP9cg=,tag:Vc3Mg+/yjguDUqG+DA483w==,type:str]
        secret_symmetric_key: ENC[AES256_GCM,data:jrQWyRW8MhzRuYtzpu987kmetUxfCfSYwnbCyIuNxzc=,iv:dQfWmQoLfr1VPaCVFLCvGsfXFAo+zDJLwZ9qQXe26h0=,tag:CloHFwv3ntSlZv2U0Z7giw==,type:str]
    opensea:
        api_key: ENC[AES256_GCM,data:t52daAVoYXsfPkByYw1PULm5QDm6s7F8ZgzVxTdF5mI=,iv:dA1jMFM/xW7LkXlbu6O/3MLxl1P4ArWSph4W4D4YCZg=,tag:T3Q1/DNC6ThLy2fYanOVxA==,type:str]
    ethereum:
        rpc_url: ENC[AES256_GCM,data:Bs2JzyeTRP7y9glocFkKRPuDQxiGf5jdBDtP1me2HuMvj/CvvbVMElsg4x9AYHviMvwR84warXzUc1StwQ==,iv:wtwZITqDJCZ5uXia+0MSTvD4ir4LQ9ElDghKS4GFYuw=,tag:ts03DFN0SianOnHh4eN2MQ==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:mk26g7kv8PeyReS9N7nwTEpbDmCPWG6MSMsFu7AL4HijPHslSNq7BnHlHAoAcOSuL0FRLO0x/ArhqM7ORJ1EV244ywFDjZI5f+kG3jnOrCJf6TuZ4Rn22DkbDKmUQ5ZSd4/iHdHqE+dxT5kCufr75FK/lWxd+E8T8PzFQ+aUorxe7jy+XQX5lgmkGlr2KVI=,iv:EVcSMB7WtXA7goyXkKqZI0jbi4zX8GeQF4+pzwy8who=,tag:4jvFhCNW2qSZHGVBi8cYsQ==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:IDfcWS9tdRNZcPF94zR2zs62WPcrztD+Q6yJEl4qNOuFi/u0X+uBkKa41VlGMHfqgNPA3icPQXJoJpX0Xw==,iv:zW+SvSwDrCFEi6x6YRLkd6eo45qu4Sr0R3s5mfko8UM=,tag:PImMSxXHOsrpMBEzmurtTw==,type:str]
    sentry:
        dsn: ""
    aws:
        access_key_id: ENC[AES256_GCM,data:gDCzP/4OKax2KmqM0fbEeLWe/tc=,iv:sHsWDUCELcxsJ+v1KHQ3Hh1tr80GrfChUws55HXz39g=,tag:nqsg8AMGmMJugg/GcoY4fw==,type:str]
        secret_access_key: ENC[AES256_GCM,data:fVPyKONHiUbumZt0Mqxl63J24Wc+dxG3s5u2dxn+yedETJy9rYpUtQ==,iv:0dKfa2ViLiiDogVs3I6SVK5HZtcrVzwo6b/rGWF4Rmw=,tag:Okbwu7mIWGflZnqBpE/Ggg==,type:str]
    jwt_pubkey: ENC[AES256_GCM,data:C285spZ9Q5/XBvPj2/DVU5L2RfyRJZucna6Alvd33MAXRR4gxXmS5KO8VZ+pHrSAeFu89LV03EWeYwiH9wAk7Bbl0SJKdL0QX7RP4/fOSFzBtMUVa2m+lflX6w57jUwMSUjGJJVqS8WtyMxCiVwDX8p4HM6XFl13MXLuev5Yqcc9Ci4Al7DVGn/Bj9ffe/XzUkX21pEXg7f8cfyG5QGR6hB8rIio8biKqwD7JqnsstlfIynGjsevRhKt2zADEtpLGDKYxYgX7OuZtceEb7gZcwXpW9YiYhCpI/Qm4LL9kW56rmsXp0IyAHHkzltG24Wle/5cWa+1K70S3ba0HgG5NZczMwMElNfJQME7ANHtvOkIBu+MTI/Pbkj2eC2VYeU3gpPBnMVn4+lm9aVTacHn2saQSmy51pGuuonLKhNXmzxTW4HnCkLL19RVcccAPQ3vl8d80JxeKJR9BgmOIAFgZ5HFwy9bVa+7rhP9HeXvmLfIqefhm5q01Or2kZF65pWwicL0iS9MYMP8/l+59cdP2+7GJXtyvD+CwtGt4/+GThf4oilv/Po9lTbyFdTAUygQ1GIy1D+v/XTnttM5HRwlpxD8cn3anFdvPDrU8x3/LJkNmy9lqpRINCp3RGYm07jpn02M23h+TjSRb0jZElM8gtwMY34UpbSIGCo6hYLxHNKzpsmJ4nnpyc6zBNBnBnvdmKvMbd5LL3X6k/0oyZsMBgXFkOygWW0irXaouQkyElEuoTeJbZ1CWNHP5Ie4XhyMJOyGuV8nj+cDWIx6pUIOEIOvbkLVp5fYpBfrg3XvYf1uYDS4uFxQ1jlopg3ZT9CjpI9XLhU6GrEAPgx4KFZY8Oh5YSH2fcj8/n5JAnf3ucqiXdcFRdUNMtnLdqic8OgJkeDetxIoXHPE1TfHPieKBfqIWct++pwj40W9hAaHAFuX3lFvcIrTApFHQW6ObaP8P208P+59/+8bf/RmcDneJlGtAiaI92Dx8MvdG0CmxPVZe2LqKQut7vhlrq9TDoaErHCHpvW32THwX4jag9OHApWr+kyqZbrVzzxmWz4heHo=,iv:s1Uhfr1NW7/NYSMRueFhLkK7iweYvzikDgYRsuY+G1o=,tag:jl+QJa6wOgMmWhIxdDbZ+Q==,type:str]
    asset_server:
        secret_key: ENC[AES256_GCM,data:JVpJAtjdQG6VKbj6fXvpC17c8EbOlzff3qdYECHwFAc=,iv:qL3wSOgYKGxFPwQmjyDcBdIwmCSxW9d60z0lmfFmOsY=,tag:Q3pjmpWtdJh53DiMr/0/8Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2023-09-26T23:27:56Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQH0YvlEPKcEXBzmGrH5kDlGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1e6g7Ha25cunPQVNAgEQgDtNizYC2Na05e/FBBUvG5uZnqlDI9FgNYeUK7mlJCLODYo1aA1EFD6YNpQ5qOqPmBg6edoQRY0A6gAaYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-26T23:27:56Z"
    mac: ENC[AES256_GCM,data:7/xJmuzp4tW+4WoqKcae6bS6pY9MWz+8xuXroeusZRb3unzrnalW5VOqegR5Tlxfm/BzJLzwhav7I60gaMO3sqfnVPitfk+47rIC7/yRA8Xh7wlXosKj1H8zonVpmrgYIJC0SbFS/mFK/jo3VJl30zp6mmpFj0MwLfMRJ1Nu4Ug=,iv:8H/L8I3EWQulcMvurIEietKpMMV38lWQqgm09g8nnOg=,tag:VXWO7PyYPLUOyrV/yH0e7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
