secrets:
    store:
        db_uri: ENC[AES256_GCM,data:fJNagwAJN1Dig+eYS5t9N9yqBTPia9ZVVS7VzvItBr1ADZs0yCEljNVTjyBYCXpfVZN0cfQC93R8E3KLdhsNEB04sJBOjehfwdWXHV1SF6qhLSnz55w267h6PaZsYoAk5WUxOw4ZJjc=,iv:68qUmrximqnBzPmt0R9G4cGd3ICOFGuVP5mJWqK7iPw=,tag:6eyVNKkn7D8gL/KC7s5jvQ==,type:str]
        db_name: ENC[AES256_GCM,data:mYYCxgkfDDxKEl8=,iv:nQ9311mPmTxvmSUnqHlwcS1BNQMSSwhl0DtFpvp7Hqw=,tag:WGJKtrWKHr18u/qEwpzN5w==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:bfLhWVDyJvWRPHDml1v1U5F8vkaoa1Yhdyh52j8QHsI=,iv:fVX22q2dNZ1JPcjg5OiWtLUD6UnCJoJ8Iov9ncCOIo8=,tag:kT/mEWCIyAwTmj7DPuiMyg==,type:str]
    opensea:
        api_key: ENC[AES256_GCM,data:4H0UsysDfymM96rmAktB9uamSb5EirqSiQMCg67IGU8=,iv:Lget8iVCMAZejL6zp2eaRYgaU5ter9q7+aHAkFipFkY=,tag:xzdDW8hId2aGDnN2It3vWA==,type:str]
    ethereum:
        rpc_url: ENC[AES256_GCM,data:A643AG1KdmSIYgN3G3sY2e+SaA7Uoh+/f+RSUtMts3rj/MkPVkLwwfyYprPseX9hEmTKMhOfBAQEFdkpOw==,iv:YkGitIMmDg9sCKQm6EgEXphSEeQKdoM8/dwsjuNWGY4=,tag:JeadkHGwYH3XQaNCHrxwWQ==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:RnC6tOfeBJzYIM5Il/62ZsY1Sjw/yr75eE+OhqMMoTDZFCYkv6aoHfz/P/3A1MJDsrwWfRWYqQQHB4H64PyuEQ4CPNPhF4y2NPDGHd2DOXh0tfGpZJ6il+3LALY+2LTK3AkLgmrQQQXN941JL5eWCdWbSo80kT8qMLGaxFWyZ/mOMRFasiEu2A59KYpE5GE=,iv:4TMoKvs6UnUw8hEyx1nM1W5QN0oanyzKDPWkRcFNI88=,tag:RZ8V90OHut/jWPvfE2bm7A==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:tnYOJWZd5hjHzm/6ddORZ2pyem2Cpi6qtlkDIGlK7Z4GhsZmuSJTVPiGiSDm1d1hw3DaZxYxBoUae6CS4w==,iv:2/BahpOcseGxEAIIj4m1YcU1QhWurExDUmxI8W5dNJ4=,tag:77xtP7YArllmNpYaPxtP8A==,type:str]
    sentry:
        dsn: ""
    aws:
        access_key_id: ENC[AES256_GCM,data:ROE7Tw==,iv:4jSA1bEke6ZIiUlPps7TEhN51+qEen/L/fFAtoi208w=,tag:zsS4xGSazxTkB5KQk65U1g==,type:str]
        secret_access_key: ENC[AES256_GCM,data:XtCziw==,iv:9I949tihUMVv3YhSyjR4ttxhWuXUNeswHkptKYgmWXU=,tag:vvRoXUvtixR4+LP9H1btQQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2022-10-12T06:13:21Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQFLevk4z9T95/m014AR+8f/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH4iAcCzekRItELWvAgEQgDt8Hi25irxI7EltmytAKv9+CuayzpKmPau0/7Nf0dGDZbCDvnINnGkcjbLzyVclkQH0TXKr4vQ+a1miLA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-12T06:13:21Z"
    mac: ENC[AES256_GCM,data:t88KSMmfK62IZVE8jbIrBqXCiXDSAwGnybD2tk1uHeokPPZttsQpUGnOEmKKNCrTG9WeF5nCxDlV1mH8UfaR+7AKRmJzg8KbY3hnkc+KN45BchC7MRJUtkKa50daJJ0IVBJmDpjg+YUN3IseeEq2tdG82b/byiPIVDCc+aEGV/U=,iv:BedjyMqHViXhUEJHXT6q3juiYvIRBC8VyWCwNDG5Hmk=,tag:65gqkVj7zs4l7tmE88IcFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
