secrets:
    store:
        db_uri: ENC[AES256_GCM,data:HNTNLpvW6nQjlXJqhVeVsySwXfLS6C79LcsE0TZ9TX7KP5bbXn3sbprnok1blIIWGWe01OrqwlNoHzYrT3oJF3H8a0PT2Qc21tJ/B00VyVFSl072lv3IKYXVTLXe8hTzWN39t7680y4=,iv:Kz+tEhpDbQPIfhsBjFqnrhkYIKIvhf/ntj8tcfXnU3g=,tag:bZZq+5/6McS9sgICvBLnIw==,type:str]
        db_name: ENC[AES256_GCM,data:P5FkyUoiK1SuONs=,iv:oRYDoLo/WfjZBMJmKG0CGO0I4SQT0dAhf1MCzmx+tiw=,tag:SVbrOHEYFr328KBsJtOY7Q==,type:str]
    server:
        api_token: ENC[AES256_GCM,data:bkknwCqzBUDiicy+vkOJB6LiJ+MSz6Peago2H72GKCI=,iv:vCFUL1KI2h6wDlfFZt2YjpmtHWe6z+qcVVHijmF9t6Y=,tag:0LHI0UwGOOLUiVl42jlHsQ==,type:str]
        admin_api_token: ENC[AES256_GCM,data:iACxWfBKlgwjkE7PiTyMdKA4IYSqe9ziNpUnRclXGtg=,iv:R2/LaA4TP7FZREKcVSCT/NHSamTQgzZsTxboCXvhrYs=,tag:3YDMSWkzsP4XEJvaqqq7EQ==,type:str]
        secret_symmetric_key: ENC[AES256_GCM,data:yaUMlu5j0MLf6FlH8MSgGn/GB6a89YQ1KBjivmtDDE0=,iv:rH+8rc91tjAab3StPZPbAAhRdRMrYxSJJkbe8InuJ+E=,tag:npMt0ATuMTL3RL000SvBVQ==,type:str]
    opensea:
        api_key: ENC[AES256_GCM,data:cyO8dhTbSCgZL0m2rHkbgzSCUpJPuxwbemEOn4Vo1cI=,iv:SjB32V3VNfy7wT0bZ9s/1EpMPKdTbhkpHC1Ec9OagYw=,tag:GgpWVEwHtI+0N7HkilyZTA==,type:str]
    ethereum:
        rpc_url: ENC[AES256_GCM,data:4CKnW4xbul93ymjNTE3WGfLkPMudI74IE6dFLGP7k8wb5+YvG+z8VY02TBFSGdPuurC5u2LHfMtwWAOL6g==,iv:rsC35PFX4xlJDwP4jKJptN65tiYHLOdNvQizOMifOlE=,tag:dle2Ww3VLP+LCkSNcqFELA==,type:str]
        worker_account_mnemonic: ENC[AES256_GCM,data:b+67NrkOgnrxrcYp1jEK9SOmCi5yseFk+q5UraiqBONSUDnD7+R3tZr+Y6AV7MLywtvjAqj9pJ2ZORBz0AzUe3rd0AIl+Fu8gV6wO/bIYGfdj3l4YkmRDHzCRpPa+of4/z5V1ATWI2QWSv7ltm2ZxCSWF55Y6FJm8s5/n58HI3X0NMnsNgiDzLen0Uu70fE=,iv:rxeSaz/Dz5ftyDZIhNpDctN3hcSmv7x/CnpuAw2v/3k=,tag:W/+2Xv7BGHkl3jo+4U36sQ==,type:str]
    ens:
        rpc_url: ENC[AES256_GCM,data:+a62wisUteESbMtvIhWTAcOnIY5g8og8RWDhlDW8bE6w58B28rc7K+0jJRNqcEsK4WiJ7GloHjDfQvRh2w==,iv:YYF4n5cM3EP1TlRjMe6Lv8YZfD2hJnonxHkxeHI5qYA=,tag:UzxTbG5ocJJmza89UtDy1A==,type:str]
    sentry:
        dsn: ""
    aws:
        access_key_id: ENC[AES256_GCM,data:Rrxv4cPKzorBiFl+vaS5GQe8E0c=,iv:mE0vg6IU5x3B/n6RVDc/CJGMIKMHKMN88132Spl/dfU=,tag:7AIjFpR656EakVPwkoe1TA==,type:str]
        secret_access_key: ENC[AES256_GCM,data:sd9OqgMr0DsO6RoucTfIm0QacAbqjTb5RabBVIxLPV4xoceFDL60ZA==,iv:R9WfHILCXnyvP/e/NJzs1VKCFblqfEVML/pPgwKiEBY=,tag:9jNx4mqRrZC1dz7IRzruqA==,type:str]
    jwt_pubkey: ENC[AES256_GCM,data:fBfGB+YyNWgiTpTKgrvB05y6jg4Kizdq/s7gy5wCgulGwB1yzuUeYRViFlB1wuDefCJMuGulWMtAfy6pUvBIXuLtp0g/JEtFhFz5xo02iXCwVnSl7V2TjuQ/AdsA+wzuAG2oVvyyfHx/0PLdJ4iDlWq5BbjyE1t93pU+HujaJw/+xxVDeolOV260x6mEH0h0uvWX+qxm20xZ6+3Qit+8wuS4xexIvWXNcb9n9TawpmE3PJe+T8ZU4JVU53dUDCG1oyGPE47Lx++QAvr990a/hoEPWWAXUrjP+hiW+Bd16GmitOlklO+08V7aR/ht1oI+bA5CuQMkjNucVAV4eCksyJp66Ds55fWLbXvLOQU4qVH9XMLCLAarX4mKE0Xs/ZTxoYNNgE5A8BdC/9+E90kc2p1P+SlXr6n+Ygk3GHzv809HrTnBU7O+CBz8Rj1Upp514e3zRLbMo+aGhs2pCRi4cGMHyJ/8gYpdtHA66cxHh9uGKGzvRvST2xAHPLTUUEmC3lZwLrqmfTCSqunN5ZZOjll0zNQmJWP8gQndxP5nw89jiR1/BLRaidClVIuZC1GAbuV279NIbH4Ve6fNT7WLe17ETapRi+Gt4MQ1XXrkN8VkVs4jwS3Ow/s94xIDJt5SuaiXxoI3EvjPSs5lqNbbJJyJTdBmRU9shNCGCLAmhaIzp72AH35mXpdGjIE6C6177aslUuxOWFCXFJIp7BzGMJ3PdEeWND1v342bIOX0dkLP3qxgxbAndrvNlABNXkyQNM4cxc5t6UoS2UJUbK5elZ9vhivceNAwhdetPEboCfCYh+ZHaCnoc15nlU67XeNLEoOLz+WezbL769+Of7zCHUKYqXcY8kXrWZWUapBd02YdehU4P2jtRkxvV4+YJE2lnxmjiYL/QfnpJ/Og7ukPA4Vn7UH2dszsRsLwBQfKorJyCZLUzmwagkKHADaarctZdCrJFUmjhKAQp4uYn1o2acCfdxWbO260gxKfeYGIgUIJCAVo9t7Am+WquwUY0UzoVeiJ77WyLN+7VasjigazBZXXlWyH7amTqvjKS/Ap5dk=,iv:CPbn2jYyAuzIyL9nKuhJ+lpTg96+MH45Y1r0yKKZLzI=,tag:SLZj0B6Y0DDC9QmDn3q1Ug==,type:str]
    asset_server:
        secret_key: ENC[AES256_GCM,data:dzAT6WbI2jC0mXmPIany6j97TcWWnrjAgxF1ZMWRnRk=,iv:nT698Z6nNpXdnfXZKlFZKN/bzdA1w9tpDkjgB72Ebno=,tag:4F17G3sjSpHESNVBYlHjmg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:083397868157:key/e8cb4c43-be28-4640-bc4b-690c9a3da787
          created_at: "2023-07-14T01:27:51Z"
          enc: AQICAHhY7Z+2OMnCoBQTzz4/wjFslTTDkNSJtLHi926x3IU7fQEzE5Xbt3BPtxQSR8J4EHSWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsJjF14/e8BQtFmN7AgEQgDvBxn8gztfP9fx/UhQXwQYyNrIGpNr+9Sq1Ra+f+VMT67OHtVmbPMT7MCTRDWw363uDxhhC+95Wf6W4Sw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T01:27:51Z"
    mac: ENC[AES256_GCM,data:Pw6+5fM+PveaCorBu3m/uRkbA8tCVT9eLlFveGgTuJZRIKUaQhwEQgRcKL3aTt0E2dlndsJmtRhl0ncyk3Y5iSHMgXCSy9kM5Ymv0NbWJT/KvqLqmTmcNwhdA8q9khVwVYhAB8w5kpi8OB09qXgz4kabokANsa4mY0bGSoR9ITQ=,iv:bZ4a3NTsUdAh9/F+XYSqT9VWh8owExzeRsc8otz3evg=,tag:+DUjRJ4Y4EQ/rSHNB7cnvA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
