# Default values for nft-indexer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 083397868157.dkr.ecr.ap-northeast-1.amazonaws.com/nft-indexer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tags:
    api: "api-0.0.16-26"
    background: "background-0.0.16-26"
    provenance_indexer: "nft-provenance-indexer-0.0.16-27"

serviceConfig:
  cadence_hostport: cadence-frontend.cadence.svc.cluster.local:7933
  cadence_domain: nft-indexer
  feralfile_api_url: https://feralfile.staging.bitmark.com
  cache_bucket_name: autonomy-cached-full-artwork-staging
  opensea_ratelimit: 1
  environment: staging
  network:
    tezos: livenet
    ethereum: livenet
    bitmark: livenet

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: true
  external_dns: true
  hosts:
    - host: indexer.staging.autonomy.io
      issuerRef:
        name: letsencrypt-aws-dns
        kind: ClusterIssuer
      paths:
        - "/"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=10886400; includeSubDomains; preload";

certificate:
  enabled: true
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
