apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-subscriber.fullname" . }}
  labels:
    {{- include "nft-event-subscriber.labels" . | nindent 4 }}
data:
  config.yaml: |
    log:
      level: {{ .Values.serviceConfig.log_level | default "info" }}

    network: {{ .Values.serviceConfig.network }}

    cadence:
      host_port: {{ .Values.serviceConfig.cadence_hostport }}
      domain: nft-indexer
      log_level: 0

    notification:
      endpoint: http://autonomy-notification.autonomy.svc.cluster.local:80

    store:
      db_name: nft_indexer
