apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nft-event-processor-tezos-emitter.fullname" . }}
  labels:
    {{- include "nft-event-processor-tezos-emitter.labels" . | nindent 4 }}
data:
  feralfile_last_stop_block_key_name: {{ .Values.serviceConfig.feralfile.lastStopBlockKeyName }}
  dappetizer.feralfile.config.json: |
    {
      "indexing": {
        "fromBlockLevel": 2845033,
        "contracts": [
          {
            "name": "FeralFileV1",
            "addresses": {{ .Values.serviceConfig.contractAddresses | toJson }}
          }
        ]
      },
      "tezosNode": {
        "url": "{{ .Values.serviceConfig.tezosNodeRPCURL }}"
      }
    }
{{- if not (empty .Values.image.tags.tezosPostcardIndexer) }}
  postcard_last_stop_block_key_name: {{ .Values.serviceConfig.postcard.lastStopBlockKeyName }}
  dappetizer.postcard.config.json: |
    {
      "indexing": {
        "fromBlockLevel": 2845033,
        "contracts": [
          {
            "name": "postcard",
            "addresses": {{ .Values.serviceConfig.postcardAddresses | toJson }}
          }
        ]
      },
      "tezosNode": {
        "url": "{{ .Values.serviceConfig.tezosNodeRPCURL }}"
      }
    }
{{- end }}
{{- if ne .Values.serviceConfig.environment "development" }}
  marketplace_last_stop_block_key_name: {{ .Values.serviceConfig.marketplace.lastStopBlockKeyName }}
  dappetizer.marketplace.config.json: |
    {
      "indexing": {
        "fromBlockLevel": 2845173,
        "contracts": [
          {
            "name": "fxhash",
            "addresses": [
              "KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE"
            ]
          },
          {
            "name": "hicetniuc",
            "addresses": [
              "KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton"
            ]
          },
          {
            "name": "versum",
            "addresses": [
              "KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW"
            ]
          },
          {
            "name": "fxhashv2",
            "addresses": [
              "KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi"
            ]
          }
        ]
      },
      "tezosNode": {
        "url": "{{ .Values.serviceConfig.tezosNodeRPCURL }}"
      }
    }
{{- end }}
