apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nft-event-processor-tezos-emitter.fullname" . }}
  labels:
    v: "1"
    {{- include "nft-event-processor-tezos-emitter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nft-event-processor-tezos-emitter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nft-event-processor-tezos-emitter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
{{- if ne .Values.serviceConfig.environment "development" }}
        - name: {{ .Chart.Name }}-tezos-indexer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.tezosMarketplaceIndexer | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEFAULT_CONFIG_PATH
              value: /.config/dappetizer.default.config.json
{{- if ne .Values.serviceConfig.eventProcessorURI "" }}
            - name: EVENT_PROCESSOR_URI
              value: {{ .Values.serviceConfig.eventProcessorURI }}
{{- end }}
{{- if ne .Values.serviceConfig.eventSubscriberURL "" }}
            - name: EVENT_SUBSCRIBER_URL
              value: {{ .Values.serviceConfig.eventSubscriberURL }}
{{- end }}
            - name: TEZOS_NODE_RPC_URL
              value: {{ .Values.serviceConfig.tezosNodeRPCURL }}
          volumeMounts:
          - name: marketplace-indexer-config
            mountPath: "/.config"
            readOnly: true
{{- end }}
        - name: {{ .Chart.Name }}-feralfile-indexer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tags.tezosFeralfileIndexer | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if eq .Values.serviceConfig.environment "development" }}
            - name: NETWORK
              value: testnet
{{- end }}
            - name: DEFAULT_CONFIG_PATH
              value: /.config/dappetizer.default.config.json
{{- if not (kindIs "invalid" .Values.serviceConfig.eventProcessorURI) }}
            - name: EVENT_PROCESSOR_URI
              value: {{ .Values.serviceConfig.eventProcessorURI }}
{{- end }}
{{- if not (kindIs "invalid" .Values.serviceConfig.eventSubscriberURL) }}
            - name: EVENT_SUBSCRIBER_URL
              value: {{ .Values.serviceConfig.eventSubscriberURL }}
{{- end }}
            - name: TEZOS_NODE_RPC_URL
              value: {{ .Values.serviceConfig.tezosNodeRPCURL }}
          volumeMounts:
          - name: feralfile-indexer-config
            mountPath: "/.config"
            readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: marketplace-indexer-config
        configMap:
          name: {{ include "nft-event-processor-tezos-emitter.fullname" . }}
          items:
          - key: "dappetizer.marketplace.config.json"
            path: "dappetizer.default.config.json"
      - name: feralfile-indexer-config
        configMap:
          name: {{ include "nft-event-processor-tezos-emitter.fullname" . }}
          items:
          - key: "dappetizer.feralfile.config.json"
            path: "dappetizer.default.config.json"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
