apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nft-event-processor-tezos-emitter.fullname" . }}
  labels:
    {{- include "nft-event-processor-tezos-emitter.labels" . | nindent 4 }}
type: Opaque
data:

