name: golangci-lint
on:
  push:
    branches:
      - main
      - develop
      - main_hotfix
  pull_request:
    branches:
      - main
      - main_hotfix
      - develop

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.7' # The Go version to download (if necessary) and use.
      - name: Setup git config for private repo
        id: setup-git-config
        env:
          GITHUB_USER: bitmark-bot
          GITHUB_TOKEN: ${{ secrets.ACTION_BOT_GITHUB_TOKEN }}
        run: |
         git config --global "url.https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          skip-cache: true
